# Generated by Django 6.0 on 2026-01-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrestrialbiocontroldispersalmonitoring",
            name="plant_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
