# Generated by Django 6.0 on 2026-02-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquaticplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aquaticplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plants", "Number of plants"),
                    ("m^3", "Volume (Cubic Meters)"),
                    ("kg", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="terrestrialplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plants", "Number of plants"),
                    ("m^3", "Volume (Cubic Meters)"),
                    ("kg", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
    ]
