# Generated by Django 6.0 on 2026-01-26 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrestrialplantobservationinfo",
            name="specific_use_code",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")], default="Unknown"
            ),
        ),
        migrations.AddField(
            model_name="terrestrialplantobservationinfo",
            name="suitable_for_biocontrol_agent",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")], default="Unknown"
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationinfo",
            name="research_observation",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")], default="Unknown"
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationinfo",
            name="soil_texture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.soiltexturecode",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationinfo",
            name="visible_well_nearby",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")], default="Unknown"
            ),
        ),
    ]
