# Generated by Django 6.0 on 2026-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waterbodydata",
            name="type",
            field=models.TextField(
                choices=[
                    ("Bog", "Bog"),
                    ("Confined Pond", "Confined Pond"),
                    ("Discharging Pond", "Discharging Pond"),
                    ("Ditch", "Ditch"),
                    ("Intertidal", "Intertidal"),
                    ("Lake", "Lake"),
                    ("River", "River"),
                    ("Slough", "Slough"),
                    ("Stream", "Stream"),
                    ("WetlandWetland", "Wetland"),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="WaterbodyType",
        ),
    ]
