# Generated by Django 6.0 on 2026-01-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLocationFoundTerrainCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."agent_location_found_terrain"',
            },
        ),
        migrations.RemoveField(
            model_name="terrestrialbiocontroldispersalmonitoring",
            name="sign_of_biocontrol_presence",
        ),
        migrations.CreateModel(
            name="LocationBiocontrolAgentsFoundTerrestrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.activity"
                    ),
                ),
                (
                    "biocontrol_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolagentcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "location_agent_found",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.agentlocationfoundterraincode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."location_biocontrol_agents_found_terrestrial"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "location_agent_found",
                            "invasive_plant",
                            "biocontrol_agent",
                            "activity",
                        ),
                        name="unique_location_biocontrol_agent",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SignOfBiocontrolPresenceTerrestrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.activity"
                    ),
                ),
                (
                    "biocontrol_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolagentcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "sign_of_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolpresencecode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."sign_of_biocontrol_presence_terrestrial"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "sign_of_presence",
                            "invasive_plant",
                            "biocontrol_agent",
                            "activity",
                        ),
                        name="unique_sign_of_biocontrol_presence",
                    )
                ],
            },
        ),
    ]
