# Generated by Django 6.0 on 2026-04-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemicalApplicationMethodDirectCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."chemical_application_method_direct"',
            },
        ),
        migrations.CreateModel(
            name="ChemicalApplicationMethodSprayCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."chemical_application_method_spray"',
            },
        ),
    ]
