# Generated by Django 6.0 on 2026-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_spreadresults_agent_density_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquatictreatmentmonitoringentry",
            name="treatment_pass",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First", "First"),
                    ("Second", "Second"),
                    ("Third", "Third"),
                    ("Greater", "Greater"),
                    ("Unknown", "Unknown"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialtreatmentmonitoringentry",
            name="treatment_pass",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First", "First"),
                    ("Second", "Second"),
                    ("Third", "Third"),
                    ("Greater", "Greater"),
                    ("Unknown", "Unknown"),
                ],
                null=True,
            ),
        ),
    ]
