# Generated by Django 6.0 on 2026-04-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_chemicalapplicationmethoddirectcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantsWithBiocontrol",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."plants_with_biocontrol"',
            },
        ),
        migrations.AlterField(
            model_name="aquaticplantobservationcontext",
            name="suitable_for_biocontrol",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="aquatictreatmentmonitoringentry",
            name="evidence_of_treatment",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")]),
        ),
        migrations.AlterField(
            model_name="chemicaltreatmentcontext",
            name="treatment_notice_signs",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="pretreatmentobservation",
            name="pre_treatment_observation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontroldispersalmonitoringentry",
            name="linear_segment",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontroldispersalmonitoringentry",
            name="suitable_for_collection",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolreleaseentry",
            name="linear_segment",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationcontext",
            name="research_observation",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                default="Unknown",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationcontext",
            name="suitable_for_biocontrol_agent",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                default="Unknown",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantobservationcontext",
            name="visible_well_nearby",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                default="Unknown",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialtreatmentmonitoringentry",
            name="evidence_of_treatment",
            field=models.CharField(choices=[("Yes", "Yes"), ("No", "No")]),
        ),
        migrations.AlterField(
            model_name="waterbodycontext",
            name="tidal_influence",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolcollectionentry",
            name="invasive_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.plantswithbiocontrol",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontroldispersalmonitoringentry",
            name="invasive_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.plantswithbiocontrol",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolreleaseentry",
            name="invasive_plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.plantswithbiocontrol",
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolreleaseentry",
            name="plant_collected_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="additional_plant_found_on",
                to="api.plantswithbiocontrol",
            ),
        ),
    ]
