# Generated by Django 6.0 on 2026-01-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_terrestrialplantobservationinfo_specific_use_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terrestrialplantobservationinfo",
            name="specific_use_code",
        ),
    ]
