# Generated by Django 6.0 on 2026-03-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_alter_aquaticplantmechanicaltreatmententry_disposed_material_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."specific_use"',
            },
        ),
        migrations.RemoveConstraint(
            model_name="wellentry",
            name="unique_well_in_activity",
        ),
        migrations.RemoveField(
            model_name="terrestrialplantobservationcontext",
            name="specific_use",
        ),
        migrations.AddField(
            model_name="wellentry",
            name="well_tag",
            field=models.CharField(
                db_comment="Identifier of a Registered Well",
                default="Unset",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="access_description",
            field=models.TextField(
                blank=True,
                db_comment="User directions to access location",
                max_length=16384,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="comment",
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="location_description",
            field=models.CharField(max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="aquaticplantobservationentry",
            name="sample_point_id",
            field=models.CharField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="aquatictreatmentmonitoringentry",
            name="comment",
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolcollectionentry",
            name="comment",
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolreleaseentry",
            name="agent_source",
            field=models.CharField(max_length=16384),
        ),
        migrations.AlterField(
            model_name="terrestrialbiocontrolreleaseentry",
            name="plant_collected_from_manual",
            field=models.CharField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="terrestrialtreatmentmonitoringentry",
            name="comment",
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
        migrations.AlterField(
            model_name="waterbodycontext",
            name="comment",
            field=models.TextField(max_length=16384),
        ),
        migrations.AlterField(
            model_name="weatherconditions",
            name="comments",
            field=models.TextField(max_length=16384),
        ),
        migrations.AddConstraint(
            model_name="wellentry",
            constraint=models.UniqueConstraint(
                fields=("activity", "well_tag"), name="unique_well_tag_for_activity"
            ),
        ),
        migrations.AddField(
            model_name="specificuse",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.activity"
            ),
        ),
        migrations.AddField(
            model_name="specificuse",
            name="specific_use",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.specificusecode",
            ),
        ),
        migrations.RemoveField(
            model_name="wellentry",
            name="well_tag_number",
        ),
        migrations.AddConstraint(
            model_name="specificuse",
            constraint=models.UniqueConstraint(
                fields=("activity", "specific_use"), name="unique_activity_specific_use"
            ),
        ),
    ]
