# Generated by Django 6.0 on 2026-01-08 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_waterbodydata_type_delete_waterbodytype"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_comment="Image file name, required for S3 fetching",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_comment="User submitted details for an image. Generally an image title",
                        max_length=256,
                    ),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."uploaded_image"',
                "db_table_comment": "Image uploads for IBC Records",
            },
        ),
    ]
