# Generated by Django 6.0 on 2026-01-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_agentlocationfoundterraincode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrestrialbiocontroldispersalmonitoring",
            name="linear_segment",
            field=models.CharField(
                blank=True,
                choices=[("Y", "Yes"), ("N", "No"), ("U", "Unknown")],
                null=True,
            ),
        ),
    ]
