# Generated by Django 6.0 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_aquatictreatmentmonitoringentry_treatment_pass_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aquaticinvasiveplantonsite",
            name="a_mech_plants_on_site",
        ),
        migrations.RemoveConstraint(
            model_name="terrestrialinvasiveplantonsite",
            name="t_mech_plants_on_site",
        ),
        migrations.AddField(
            model_name="aquatictreatmentmonitoringentry",
            name="monitoring_evidence_codes",
            field=models.CharField(
                blank=True,
                db_comment="This should be refactored as an FK, but it is multivalued (comma-separated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="terrestrialtreatmentmonitoringentry",
            name="monitoring_evidence_codes",
            field=models.CharField(
                blank=True,
                db_comment="This should be refactored as an FK, but it is multivalued (comma-separated)",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="terrestrialinvasiveplantonsite",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="terrestrialinvasiveplantonsite",
            name="invasive_plant",
        ),
        migrations.RemoveField(
            model_name="terrestrialinvasiveplantonsite",
            name="invasive_plant_on_site",
        ),
        migrations.DeleteModel(
            name="AquaticInvasivePlantOnSite",
        ),
        migrations.DeleteModel(
            name="TerrestrialInvasivePlantOnSite",
        ),
    ]
