# Generated by Django 6.0 on 2026-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_specificuse_remove_wellentry_unique_well_in_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="migration_remarks",
            field=models.TextField(blank=True, max_length=16384, null=True),
        ),
    ]
