# Generated by Django 6.0 on 2026-01-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_terrestrialplantobservationinfo_specific_use_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="terrestrialobservationspecificuse",
            name="activity",
        ),
        migrations.RemoveField(
            model_name="terrestrialobservationspecificuse",
            name="specific_use",
        ),
        migrations.DeleteModel(
            name="SuitableForBiocontrol",
        ),
        migrations.DeleteModel(
            name="TerrestrialObservationSpecificUse",
        ),
    ]
