# Generated by Django 6.0 on 2026-01-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AquaticTreatmentMonitoringInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_of_treatment",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")]),
                ),
                (
                    "treatment_pass",
                    models.CharField(
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Greater", "Greater"),
                            ("Unknown", "Unknown"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
                (
                    "invasive_plants_on_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invasiveplantsonsitecode",
                    ),
                ),
                (
                    "management_efficacy_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.efficacymanagementratingcode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."aq_treatment_monitoring_info"',
            },
        ),
        migrations.CreateModel(
            name="TerrestrialObservationSpecificUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
                (
                    "specific_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.specificusecode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."terrestrial_plant_specific_use"',
                "db_table_comment": "Notable land uses or attributed within the observation area",
            },
        ),
        migrations.CreateModel(
            name="TerrestrialTreatmentMonitoringInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_of_treatment",
                    models.CharField(choices=[("Y", "Yes"), ("N", "No")]),
                ),
                (
                    "treatment_pass",
                    models.CharField(
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Greater", "Greater"),
                            ("Unknown", "Unknown"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=256, null=True)),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "invasive_plants_on_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invasiveplantsonsitecode",
                    ),
                ),
                (
                    "management_efficacy_rating",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.efficacymanagementratingcode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."ter_treatment_monitoring_info"',
            },
        ),
    ]
