# Generated by Django 6.0 on 2026-01-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_terrestrialobservationspecificuse_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrestrialplantobservationinfo",
            name="specific_use",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.specificusecode",
            ),
        ),
    ]
