# Generated by Django 6.0 on 2026-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_activity_migration_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemtreatmentcontext",
            name="pesticide_use_permit",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
