# Generated by Django 6.0 on 2026-05-04 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_cache_schema"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedRasterTile",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2026, 6, 3, 3, 21, 16, 171722),
                        null=True,
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("data", models.BinaryField(max_length=524288)),
            ],
            options={
                "db_table": '"cache"."raster_tile"',
            },
        ),
    ]
