# Generated by Django 6.0 on 2026-01-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_aquatictreatmentmonitoringinformation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aquaticvoucherspecimen",
            old_name="voucher_sample_id",
            new_name="old_voucher_sample_id",
        ),
        migrations.RenameField(
            model_name="terrestrialvoucherspecimen",
            old_name="voucher_sample_id",
            new_name="old_voucher_sample_id",
        ),
    ]
