# Generated by Django 6.0 on 2026-05-04 07:45

import datetime
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_cachedrastertile"),
    ]

    operations = [
        migrations.CreateModel(
            name="RasterMapGenerationRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now=True)),
                ("bounds", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                (
                    "minimum_zoom",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(24)]
                    ),
                ),
                (
                    "maximum_zoom",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(24)]
                    ),
                ),
                ("tile_definition_source_name", models.CharField(max_length=255)),
                ("file_name", models.CharField(blank=True, max_length=512, null=True)),
                ("status", models.CharField(default="PENDING", max_length=32)),
            ],
            options={
                "db_table": '"activity"."raster_map_generation_request"',
            },
        ),
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 3, 7, 45, 48, 148708, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
