# Generated by Django 6.0 on 2026-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    def copyreverse(apps, schema_editor):
        vt = apps.get_model("api", "TerrestrialVoucherSpecimen")
        va = apps.get_model("api", "AquaticVoucherSpecimen")

        for model in [vt, va]:
            for specimen in model.objects.all():
                try:
                    specimen.old_voucher_sample_id = int(specimen.voucher_sample_id)
                    specimen.save()
                except Exception:
                    print("Reverse migration failed for {specimen.activity_id}")

    def copyvals(apps, schema_editor):
        vt = apps.get_model("api", "TerrestrialVoucherSpecimen")
        va = apps.get_model("api", "AquaticVoucherSpecimen")

        for model in [vt, va]:
            for specimen in model.objects.all():
                specimen.voucher_sample_id = str(specimen.old_voucher_sample_id)
                specimen.save()

    dependencies = [
        (
            "api",
            "0006_rename_voucher_sample_id_aquaticvoucherspecimen_old_voucher_sample_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aquaticvoucherspecimen",
            name="voucher_sample_id",
            field=models.CharField(default="temp", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="terrestrialvoucherspecimen",
            name="voucher_sample_id",
            field=models.CharField(default="temp", max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(copyvals, reverse_code=copyreverse),
        migrations.RemoveField(
            model_name="aquaticvoucherspecimen",
            name="old_voucher_sample_id",
        ),
        migrations.RemoveField(
            model_name="terrestrialvoucherspecimen",
            name="old_voucher_sample_id",
        ),
    ]
