# Generated by Django 6.0 on 2026-05-04 07:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rastermapgenerationrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 3, 7, 47, 43, 668930, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="file_name",
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="maximum_zoom",
            field=models.PositiveSmallIntegerField(
                default=15, validators=[django.core.validators.MaxValueValidator(24)]
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="minimum_zoom",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(24)]
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="tile_definition_source_name",
            field=models.CharField(default="esri-world-imagery", max_length=255),
        ),
    ]
