# Generated by Django 6.0 on 2026-01-14 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_aquaticvoucherspecimen_old_voucher_sample_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AquaticMechanicalAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorization_information",
                    models.CharField(
                        blank=True,
                        db_comment="description of authorization permit for in-stream work",
                        null=True,
                    ),
                ),
                (
                    "activity_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."aquatic_mechanical_authorization"',
            },
        ),
    ]
