# Generated by Django 6.0 on 2026-05-04 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_cachedrastertile_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="cache_hits",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="Used to track caching effectiveness. May be removed in future",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="tiles_downloaded",
            field=models.PositiveIntegerField(
                db_comment="Number of tiles downloaded. Updated periodically during download operation for progress reporting",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 3, 8, 19, 41, 82030, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
