# Generated by Django 6.0 on 2026-01-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_aquaticmechanicalauthorization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aquaticplantmechanicaltreatment",
            name="details",
        ),
    ]
