# Generated by Django 6.0 on 2026-05-05 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rastermapgenerationrequest_cache_hits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 4, 10, 22, 53, 337690, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
