# Generated by Django 6.0 on 2026-01-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_aquaticplantmechanicaltreatment_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentEfficacyRatingCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."treatment_efficacy_rating"',
            },
        ),
        migrations.RemoveField(
            model_name="aquatictreatmentmonitoringinformation",
            name="invasive_plants_on_site",
        ),
        migrations.RemoveField(
            model_name="terrestrialtreatmentmonitoringinformation",
            name="invasive_plants_on_site",
        ),
        migrations.AddField(
            model_name="aquatictreatmentmonitoringinformation",
            name="treatment_efficacy_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.treatmentefficacyratingcode",
            ),
        ),
        migrations.AddField(
            model_name="terrestrialtreatmentmonitoringinformation",
            name="treatment_efficacy_rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.treatmentefficacyratingcode",
            ),
        ),
        migrations.CreateModel(
            name="AquaticInvasivePlantOnSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
                (
                    "invasive_plant_on_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invasiveplantsonsitecode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."aq_plant_on_site"',
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "activity_id",
                            "invasive_plant",
                            "invasive_plant_on_site",
                        ),
                        name="a_mech_plants_on_site",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TerrestrialInvasivePlantOnSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitybasic",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "invasive_plant_on_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invasiveplantsonsitecode",
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."ter_plant_on_site"',
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "activity_id",
                            "invasive_plant",
                            "invasive_plant_on_site",
                        ),
                        name="t_mech_plants_on_site",
                    )
                ],
            },
        ),
    ]
