# Generated by Django 6.0 on 2026-05-08 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_cachedrastertile_expires"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": '"authentication"."role"',
            },
        ),
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 7, 6, 41, 24, 829294, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                db_table='"authentication"."user_roles"', to="api.role"
            ),
        ),
    ]
