# Generated by Django 6.0 on 2026-01-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_treatmentefficacyratingcode_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="nearestwell",
            constraint=models.UniqueConstraint(
                fields=("activity_id", "well_tag_number"),
                name="unique_well_in_activity",
            ),
        ),
    ]
