# Generated by Django 6.0 on 2026-05-08 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_role_alter_cachedrastertile_expires_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 7, 6, 49, 11, 423458, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
