# Generated by Django 6.0 on 2026-05-08 07:13

from django.db import migrations
from django.db.migrations import RunPython

from api.constants import WellKnownRoles


def up(apps, schema_editor):
    Role = apps.get_model("api", "Role")
    db_alias = schema_editor.connection.alias
    Role.objects.using(db_alias).create(name=WellKnownRoles.ADMINISTRATOR.value)


def down(apps, schema_editor):
    Role = apps.get_model("api", "Role")
    db_alias = schema_editor.connection.alias
    Role.objects.using(db_alias).filter(
        name=WellKnownRoles.ADMINISTRATOR.value
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_cachedrastertile_expires"),
    ]

    operations = [RunPython(up, down)]
