# Generated by Django 6.0 on 2026-05-08 07:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_create_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_comment="Optional owner of this map generation request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 7, 7, 40, 51, 891661, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
