# Generated by Django 6.0 on 2026-05-11 06:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rastermapgenerationrequest_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rastermapgenerationrequest",
            name="cache_hits",
        ),
        migrations.RemoveField(
            model_name="rastermapgenerationrequest",
            name="tiles_downloaded",
        ),
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, db_column="updated_at", db_comment="Updated timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2026, 6, 10, 6, 34, 43, 930761, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="created_at",
                db_comment="Creation timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                db_comment="Owner of this record (nullable)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MapGenerationIntermediateResult",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        db_comment="Creation timestamp",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="updated_at",
                        db_comment="Updated timestamp",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tiles_downloaded",
                    models.PositiveIntegerField(
                        db_comment="Number of tiles downloaded. Updated periodically during download operation for progress reporting",
                        default=0,
                    ),
                ),
                (
                    "cache_hits",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Used to track caching effectiveness. May be removed in future",
                        null=True,
                    ),
                ),
                (
                    "cache_misses",
                    models.PositiveIntegerField(
                        blank=True,
                        db_comment="Used to track caching effectiveness. May be removed in future",
                        null=True,
                    ),
                ),
                ("remaining_tiles", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status_information",
                    models.TextField(
                        db_comment="Diagnostic information from the map generation processor",
                        default="",
                    ),
                ),
                (
                    "generation_request",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Optional map generation request that caused this record to be created (may be null for system-generated maps)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.rastermapgenerationrequest",
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Owner of this record (nullable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."raster_map_generation_intermediate_result"',
            },
        ),
        migrations.CreateModel(
            name="MapGenerationRecord",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="created_at",
                        db_comment="Creation timestamp",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="updated_at",
                        db_comment="Updated timestamp",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "expires",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Datetime after which this record may be deleted to reclaim space",
                        null=True,
                    ),
                ),
                (
                    "generation_request",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Optional map generation request that caused this record to be created (may be null for system-generated maps)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.rastermapgenerationrequest",
                        unique=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Owner of this record (nullable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."raster_map_generation_rcord"',
            },
        ),
    ]
