# Generated by Django 6.0 on 2026-05-11 06:37

import api.models.cache.cached
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_rastermapgenerationrequest_cache_hits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedrastertile",
            name="expires",
            field=models.DateTimeField(
                blank=True,
                default=api.models.cache.cached.default_expiry_time,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mapgenerationintermediateresult",
            name="generation_request",
            field=models.OneToOneField(
                blank=True,
                db_comment="Optional map generation request that caused this record to be created (may be null for system-generated maps)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.rastermapgenerationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="mapgenerationrecord",
            name="generation_request",
            field=models.OneToOneField(
                blank=True,
                db_comment="Optional map generation request that caused this record to be created (may be null for system-generated maps)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.rastermapgenerationrequest",
            ),
        ),
    ]
