# Generated by Django 6.0 on 2026-05-11 06:56

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_cachedrastertile_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="bounds",
            field=django.contrib.gis.db.models.fields.PolygonField(
                default=None, srid=4326
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="maximum_zoom",
            field=models.PositiveSmallIntegerField(
                default=15, validators=[django.core.validators.MaxValueValidator(24)]
            ),
        ),
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="minimum_zoom",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(24)]
            ),
        ),
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="raster",
            field=models.BooleanField(
                db_comment="True if this is a raster map (false for vector)",
                default=True,
            ),
        ),
    ]
