# Generated by Django 6.0 on 2026-05-20 19:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.db.models.functions import Transform


def populate_vector_tile_shapes(apps, schema_editor):
    Activity = apps.get_model("api", "Activity")
    Activity.objects.update(computed_tile_shape=Transform("shape", 3857))


from django.db import migrations


def populate_invasive_plant_codes(apps, schema_editor):
    Activity = apps.get_model("api", "Activity")

    PATH_TO_PLANT_MAP = {
        "Observation_Plant_Aquatic": ["aquaticplantobservationentry_set"],
        "Observation_Plant_Terrestrial": ["terrestrialplantobservationentries_set"],
        "Treatment_Chemical_Plant_Aquatic": [
            "chemicaltreatmentaquaticinvasiveplantrecord_set"
        ],
        "Treatment_Chemical_Plant_Terrestrial": [
            "chemicaltreatmentterrestrialinvasiveplantrecord_set"
        ],
        "Treatment_Mechanical_Plant_Aquatic": [
            "aquaticplantmechanicaltreatmententry_set"
        ],
        "Treatment_Mechanical_Plant_Terrestrial": [
            "terrestrialplantmechanicaltreatmententry_set"
        ],
        "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial": [
            "terrestrialbiocontroldispersalmonitoringentry_set"
        ],
        "Monitoring_Biocontrol_Release_Plant_Terrestrial": [
            "terrestrialbiocontroldispersalmonitoringentry_set"
        ],
        "Monitoring_Chemical_Plant_Terrestrial_Aquatic": [
            "terrestrialtreatmentmonitoringentry_set",
            "aquatictreatmentmonitoringentry_set",
        ],
        "Monitoring_Mechanical_Plant_Terrestrial_Aquatic": [
            "terrestrialtreatmentmonitoringentry_set",
            "aquatictreatmentmonitoringentry_set",
        ],
        "Biocontrol_Collection": ["terrestrialbiocontrolcollectionentry_set"],
        "Biocontrol_Release": ["terrestrialbiocontrolreleaseentry_set"],
    }

    all_prefetches = set()
    for sets in PATH_TO_PLANT_MAP.values():
        for relation_set in sets:
            all_prefetches.add(
                f"activitydatarecord_set__{relation_set}__invasive_plant"
            )

    queryset = Activity.objects.filter(
        subtype__in=PATH_TO_PLANT_MAP.keys()
    ).prefetch_related("activitydatarecord_set", *all_prefetches)

    chunk_size = 1000
    offset = 0

    while True:
        activities_chunk = list(queryset[offset : offset + chunk_size])
        if not activities_chunk:
            break

        print(f"Processing activities {offset} to {offset + len(activities_chunk)}...")

        for activity in activities_chunk:
            destinations = PATH_TO_PLANT_MAP.get(activity.subtype)
            all_plant_codes = set()

            # This loop now reads entirely from RAM cache, making it lightning fast
            for record in activity.activitydatarecord_set.all():
                for destination in destinations:
                    entries = getattr(record, destination).all()
                    for entry in entries:
                        if entry.invasive_plant and entry.invasive_plant.code:
                            all_plant_codes.add(entry.invasive_plant.code)

            if all_plant_codes:
                sorted_codes = sorted(list(all_plant_codes))
                activity.computed_map_symbol = ", ".join(filter(None, sorted_codes))
                activity.save(update_fields=["computed_map_symbol"])

        offset += chunk_size


def rollback_invasive_plant_codes(apps, schema_editor):
    Activity = apps.get_model("api", "Activity")
    Activity.objects.all().update(computed_map_symbol=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_mapgenerationrecord_bounds_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="computed_map_symbol",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="computed_tile_shape",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                db_comment="Baked spatial reference for vector tiles generation.",
                null=True,
                srid=3857,
            ),
        ),
        migrations.RunPython(
            populate_vector_tile_shapes, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            populate_invasive_plant_codes, reverse_code=rollback_invasive_plant_codes
        ),
    ]
