# Generated by Django 6.0 on 2026-05-20 20:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_activity_computed_map_symbol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="computed_map_symbol",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="activity",
            name="computed_tile_shape",
            field=django.contrib.gis.db.models.fields.GeometryField(
                blank=True,
                db_comment="Baked spatial reference for vector tiles generation.",
                srid=3857,
            ),
        ),
    ]
