# Generated by Django 6.0 on 2026-06-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_activity_computed_map_symbol_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="mapgenerationintermediateresult",
            table_comment="Temporary record with intermediate results of generation request (for reporting download progress to client, and cache statistics tracking)",
        ),
        migrations.AlterModelTableComment(
            name="mapgenerationrecord",
            table_comment="Permanent record of generated raster maps (both public and private)",
        ),
        migrations.AlterModelTableComment(
            name="rastermapgenerationrequest",
            table_comment="Request for generation of raster map, with bounds and zoom level, along with the status of the request.",
        ),
        migrations.AddField(
            model_name="mapgenerationintermediateresult",
            name="seconds_elapsed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mapgenerationrecord",
            name="trip_name",
            field=models.CharField(
                db_comment="Optional trip name, used as a client-side identifier. Eventually to be replaced with server-side trip reference",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="trip_name",
            field=models.CharField(
                db_comment="Optional trip name, used as a client-side identifier. Eventually to be replaced with server-side trip reference",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="mapgenerationrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", False), ("trip_name__isnull", False)
                ),
                fields=("owner", "trip_name"),
                name="raster_map_generation_record_trip_name_unique_if_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="rastermapgenerationrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", False), ("trip_name__isnull", False)
                ),
                fields=("owner", "trip_name"),
                name="raster_map_generation_request_trip_name_unique_if_not_null",
            ),
        ),
    ]
