# Generated by Django 6.0 on 2026-06-08 10:02

import api.models.map_generation.map_generation_record
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_mapgenerationintermediateresult_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapgenerationrecord",
            name="trip_name",
            field=models.CharField(
                db_comment="trip name, used as a client-side identifier. Eventually to be replaced with server-side trip reference",
                default=api.models.map_generation.map_generation_record.generate_legacy_trip_name,
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="rastermapgenerationrequest",
            name="trip_name",
            field=models.CharField(
                db_comment="trip name, used as a client-side identifier. Eventually to be replaced with server-side trip reference",
                default=api.models.map_generation.map_generation_record.generate_legacy_trip_name,
                max_length=256,
            ),
        ),
    ]
