# Generated by Django 6.0 on 2026-06-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_mapgenerationrecord_trip_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rastermapgenerationrequest",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                db_comment="The id assigned by celery when the task is scheduled. can be used to track execution status",
                max_length=128,
                null=True,
            ),
        ),
    ]
