# Generated by Django 6.0 on 2026-06-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rastermapgenerationrequest_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateField(
                db_comment="Date (not including time information, to reduce database updates) the user last authenticated.",
                null=True,
            ),
        ),
    ]
