# Generated by Django 6.0 on 2026-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rastermapgenerationrequest_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicaltreatmentcontext",
            name="pest_management_plan_manual",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
