# Generated by Django 6.0 on 2026-06-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_user_display_name_user_email_user_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemicaltreatmentcontext",
            name="pest_management_plan_manual",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
