# Generated by Django 6.0 on 2026-06-29 20:00

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_chemicaltreatmentcontext_pest_management_plan_manual"),
    ]

    operations = [
        migrations.RunSQL(
            # language=PostgreSQL
            sql="""
            create schema if not exists "draft_activity";
            """,
            reverse_sql=
            # language=PostgreSQL
            """
            drop schema if exists "draft_activity";
            """,
        ),
        migrations.CreateModel(
            name="DraftFundingAgency",
            fields=[
                (
                    "fundingagency_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.fundingagency",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."funding_agency"',
                "db_table_comment": "Agencies funding the activity.",
            },
            bases=("api.fundingagency", models.Model),
        ),
        migrations.CreateModel(
            name="DraftActivity",
            fields=[
                (
                    "batch_id",
                    models.PositiveBigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "batch_row_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        db_comment="Row on uploaded document",
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "location_description",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                ("area_m", models.PositiveBigIntegerField(blank=True, null=True)),
                ("utm_zone", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("utm_easting", models.PositiveBigIntegerField(blank=True, null=True)),
                ("utm_northing", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "shape",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "creating_platform",
                    models.CharField(
                        choices=[
                            ("Ios", "Ios"),
                            ("Android", "Android"),
                            ("Batch", "Batch"),
                            ("Web", "Web"),
                            ("Unknown", "Unknown"),
                        ],
                        db_comment="Device form was originally created on (IOS, Android, Batch, etc...)",
                        db_index=True,
                        default="Unknown",
                        max_length=100,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_id",
                    models.CharField(
                        db_comment="User Readable formatted ID",
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Observation", "Observation"),
                            ("Treatment", "Treatment"),
                            ("Monitoring", "Monitoring"),
                            ("Biocontrol", "Biocontrol"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        choices=[
                            ("Biocontrol_Collection", "Biocontrol_Collection"),
                            ("Biocontrol_Release", "Biocontrol_Release"),
                            (
                                "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial",
                                "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial",
                            ),
                            (
                                "Monitoring_Biocontrol_Release_Plant_Terrestrial",
                                "Monitoring_Biocontrol_Release_Plant_Terrestrial",
                            ),
                            (
                                "Monitoring_Chemical_Plant_Terrestrial_Aquatic",
                                "Monitoring_Chemical_Plant_Terrestrial_Aquatic",
                            ),
                            (
                                "Monitoring_Mechanical_Plant_Terrestrial_Aquatic",
                                "Monitoring_Mechanical_Plant_Terrestrial_Aquatic",
                            ),
                            ("Observation_Mussels", "Observation_Mussels"),
                            ("Observation_Plant_Aquatic", "Observation_Plant_Aquatic"),
                            (
                                "Observation_Plant_Terrestrial",
                                "Observation_Plant_Terrestrial",
                            ),
                            ("Officer_Shift", "Officer_Shift"),
                            (
                                "Treatment_Chemical_Plant_Aquatic",
                                "Treatment_Chemical_Plant_Aquatic",
                            ),
                            (
                                "Treatment_Chemical_Plant_Terrestrial",
                                "Treatment_Chemical_Plant_Terrestrial",
                            ),
                            (
                                "Treatment_Mechanical_Plant_Aquatic",
                                "Treatment_Mechanical_Plant_Aquatic",
                            ),
                            (
                                "Treatment_Mechanical_Plant_Terrestrial",
                                "Treatment_Mechanical_Plant_Terrestrial",
                            ),
                        ]
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("created_by", models.CharField(db_index=True, max_length=64)),
                (
                    "form_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Flagged", "Flagged"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=16384, null=True)),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("received_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "migration_remarks",
                    models.TextField(blank=True, max_length=16384, null=True),
                ),
                (
                    "access_description",
                    models.TextField(
                        blank=True,
                        db_comment="User directions to access location",
                        max_length=16384,
                        null=True,
                    ),
                ),
                (
                    "linked_activities",
                    models.ManyToManyField(
                        db_table='"draft_activity"."linked_activities"',
                        to="api.draftactivity",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."activity"',
                "db_table_comment": "Base fields for an activity. All records contain this information",
                "ordering": ["date", "received_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DraftActivityDataRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivity",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."data_record"',
                "db_table_comment": "Represents a unit of form data associated with an activity (such as a participant or observation).",
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticMechanicalAuthorization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "authorization_information",
                    models.CharField(
                        blank=True,
                        db_comment="description of authorization permit for in-stream work",
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."mechanical_authorization_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticPlantMechanicalTreatmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposed_material_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plants", "Number of plants"),
                            ("m^3", "Volume (Cubic Meters)"),
                            ("kg", "Weight (kg)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "disposed_material_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("treated_area_msq", models.FloatField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "disposal_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.disposalmethodcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
                (
                    "mechanical_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantmechanicaltreatmentmethodcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."treatment_mechanical_entries_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticPlantObservationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suitable_for_biocontrol",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."observation_context_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticPlantObservationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_point_id",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                (
                    "observation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Positive", "Positive Observation"),
                            ("Negative", "Negative Observation"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "density",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.densitycode",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.distributioncode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
                (
                    "life_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantlifestagecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."observation_entries_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticTreatmentMonitoringEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_pass",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Greater", "Greater"),
                            ("Unknown", "Unknown"),
                        ],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=16384, null=True)),
                (
                    "evidence_of_treatment",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], null=True
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
                (
                    "management_efficacy_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.efficacymanagementratingcode",
                    ),
                ),
                (
                    "treatment_efficacy_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.treatmentefficacyratingcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."monitoring_treatment_entries_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftAquaticVoucherSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_sample_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_collected", models.DateField(blank=True, null=True)),
                ("date_verified", models.DateField(blank=True, null=True)),
                ("herbarium", models.CharField(blank=True, null=True)),
                ("accession_number", models.CharField(blank=True, null=True)),
                ("completed_by_person", models.CharField(blank=True, null=True)),
                ("completed_by_org", models.CharField(blank=True, null=True)),
                ("utm_zone", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("utm_easting", models.PositiveBigIntegerField(blank=True, null=True)),
                ("utm_northing", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aquaticplantcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."voucher_specimen_pa"',
            },
        ),
        migrations.CreateModel(
            name="DraftEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.employercode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."employer"',
                "db_table_comment": "Employer of the person filling out the activity form. Generally a 1:1 Relation.",
            },
        ),
        migrations.CreateModel(
            name="DraftInvasivePlantsOnSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "invasive_plants_on_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.invasiveplantsonsitecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."invasive_plants_on_site"',
            },
        ),
        migrations.CreateModel(
            name="DraftJurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent_covered", models.SmallIntegerField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.jurisdictioncode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."jurisdiction"',
                "db_table_comment": "Jurisdiction where the activity was conducted.",
            },
        ),
        migrations.CreateModel(
            name="DraftLocationBiocontrolAgentsFoundTerrestrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "location_agent_found",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.agentlocationfoundterraincode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."bioagent_location_found_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftMicrositeCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "mesoslope_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.mesoslopepositioncode",
                    ),
                ),
                (
                    "site_surface_shape",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.sitesurfaceshapecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."microsite_conditions"',
            },
        ),
        migrations.CreateModel(
            name="DraftParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "pac_number",
                    models.CharField(
                        blank=True,
                        db_comment="Pesticide Application Number (if applicable)",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."participant"',
                "db_table_comment": "A Participant is any individual who participated in an activity. They may not be an application user",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DraftPretreatmentObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pre_treatment_observation",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."observation_pre_treatment_p"',
                "db_table_comment": "Detail that an Observation has taken place before any known Treatments have occured",
            },
        ),
        migrations.CreateModel(
            name="DraftProjectCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."project_code"',
                "db_table_comment": "Project codes can be created for a user to organize their records in a way meaningful to them",
            },
        ),
        migrations.CreateModel(
            name="DraftShorelineTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent_covered", models.SmallIntegerField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "shoreline_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.shorelinetypecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."shoreline_types"',
                "db_table_comment": "Details of surrounding area for a terrestrial activity.",
            },
        ),
        migrations.CreateModel(
            name="DraftSignOfBiocontrolPresenceTerrestrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "sign_of_presence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolpresencecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."sign_of_bioagent_presence_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftSpecificUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "specific_use",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.specificusecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."specific_use"',
            },
        ),
        migrations.CreateModel(
            name="DraftSpreadResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_density",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "plant_attack",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "max_spread_distance_m",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_spread_aspect_deg",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(360)],
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."spread_results"',
            },
        ),
        migrations.CreateModel(
            name="DraftTargetPlantHeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height_cm",
                    models.IntegerField(
                        db_comment="Heights of the largest plants at a given site"
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."target_plant_heights"',
            },
        ),
        migrations.CreateModel(
            name="DraftTargetPlantPhenology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winter_dormant",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "seedlings",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "rosettes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "bolts",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "flowering",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "seeds_forming",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "senescent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."target_plant_phenology"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialBiocontrolAgentCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_estimate", models.BooleanField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.bioagentlifestagecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."biocontrol_agent_count_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialBiocontrolAgentCountExtended",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_estimate", models.BooleanField()),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "agent_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.agentlocationfoundcode",
                    ),
                ),
                (
                    "plant_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantpositioncode",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.bioagentlifestagecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."biocontrol_agent_count_extended_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialBiocontrolCollectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "historical_iapp_site",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "plant_count_collection",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_sweeps",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("comment", models.TextField(blank=True, max_length=16384, null=True)),
                (
                    "collection_type",
                    models.CharField(
                        blank=True,
                        choices=[("Timed", "Timed"), ("Count", "Count")],
                        null=True,
                    ),
                ),
                (
                    "time_collection_duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("start_time_collecting", models.DateTimeField(blank=True, null=True)),
                ("end_time_collecting", models.DateTimeField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "biological_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolagentcode",
                    ),
                ),
                (
                    "collection_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.bioagentcollectionmethodcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantswithbiocontrol",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."biocontrol_collection_entries_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialBiocontrolDispersalMonitoringEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "count_duration_minutes",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_sweeps",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "linear_segment",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                (
                    "suitable_for_collection",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                ("biocontrol_present", models.BooleanField(blank=True, null=True)),
                (
                    "monitoring_type",
                    models.CharField(
                        blank=True,
                        choices=[("Timed", "Timed"), ("Count", "Count")],
                        null=True,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "biocontrol_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolagentcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantswithbiocontrol",
                    ),
                ),
                (
                    "monitoring_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.bioagentmonitoringmethodcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."monitoring_biocontrol_dispersal_entries_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialBiocontrolReleaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_date", models.DateTimeField(blank=True, null=True)),
                (
                    "plant_collected_from_manual",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                (
                    "linear_segment",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                ("mortality", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "agent_source",
                    models.CharField(blank=True, max_length=16384, null=True),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "biocontrol_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.biocontrolagentcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantswithbiocontrol",
                    ),
                ),
                (
                    "plant_collected_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_additional_plant_found_on",
                        to="api.plantswithbiocontrol",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."biocontrol_release_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialPlantMechanicalTreatmentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disposed_material_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plants", "Number of plants"),
                            ("m^3", "Volume (Cubic Meters)"),
                            ("kg", "Weight (kg)"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "disposed_material_amount",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("treated_area_msq", models.FloatField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "disposal_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.disposalmethodcode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "mechanical_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantmechanicaltreatmentmethodcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."treatment_mechanical_entries_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialPlantObservationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suitable_for_biocontrol_agent",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        default="Unknown",
                        null=True,
                    ),
                ),
                (
                    "research_observation",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        default="Unknown",
                        null=True,
                    ),
                ),
                (
                    "visible_well_nearby",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        default="Unknown",
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "aspect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.aspectcode",
                    ),
                ),
                (
                    "slope_percent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.slopepercentcode",
                    ),
                ),
                (
                    "soil_texture",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.soiltexturecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."observation_context_pt"',
                "db_table_comment": "Details of surrounding area for a terrestrial activity.",
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialPlantObservationEntries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Positive", "Positive Observation"),
                            ("Negative", "Negative Observation"),
                        ],
                        db_comment="The invasive plant in this record was [not] seen at the site.",
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "density",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.densitycode",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.distributioncode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "life_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.plantlifestagecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."observation_entries_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialTreatmentMonitoringEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_pass",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("First", "First"),
                            ("Second", "Second"),
                            ("Third", "Third"),
                            ("Greater", "Greater"),
                            ("Unknown", "Unknown"),
                        ],
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=16384, null=True)),
                (
                    "evidence_of_treatment",
                    models.CharField(
                        blank=True, choices=[("Yes", "Yes"), ("No", "No")], null=True
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
                (
                    "management_efficacy_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.efficacymanagementratingcode",
                    ),
                ),
                (
                    "treatment_efficacy_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.treatmentefficacyratingcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."monitoring_treatment_entries_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftTerrestrialVoucherSpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voucher_sample_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("date_collected", models.DateField(blank=True, null=True)),
                ("date_verified", models.DateField(blank=True, null=True)),
                ("herbarium", models.CharField(blank=True, null=True)),
                ("accession_number", models.CharField(blank=True, null=True)),
                ("completed_by_person", models.CharField(blank=True, null=True)),
                ("completed_by_org", models.CharField(blank=True, null=True)),
                ("utm_zone", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("utm_easting", models.PositiveBigIntegerField(blank=True, null=True)),
                ("utm_northing", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.terrestrialplantcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."voucher_specimen_pt"',
            },
        ),
        migrations.CreateModel(
            name="DraftUploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        db_comment="Image file name, required for S3 fetching",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_comment="User submitted details for an image. Generally an image title",
                        max_length=256,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."uploaded_image"',
                "db_table_comment": "Image uploads for IBC Records",
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyAdjacentLandUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "waterbody_adjacent_land_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.adjacentlandusecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_adjacent_land_use"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_gazetted",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("name_local", models.CharField(blank=True, max_length=256, null=True)),
                ("access", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "max_depth_m",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "secchi_depth",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("colour", models.CharField(blank=True, max_length=64, null=True)),
                ("comment", models.TextField(blank=True, max_length=16384, null=True)),
                (
                    "tidal_influence",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                        null=True,
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodytypecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."waterbody_context"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyInflowPermanent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "flow_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodyflowcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_inflow_p"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyInflowSeasonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "flow_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodyflowseasonalcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_inflow_s"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyLevelManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "waterlevel_management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterlevelmanagement",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_level_management"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyOutflowPermanent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "flow_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodyflowcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_outflow_p"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyOutflowSeasonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "flow_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodyflowcode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_outflow_s"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodySubstrateType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "substrate_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodysubstratecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."waterbody_substrate"',
            },
        ),
        migrations.CreateModel(
            name="DraftWaterbodyUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "waterbody_use",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.waterbodyusecode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."water_use"',
            },
        ),
        migrations.CreateModel(
            name="DraftWeatherConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.TextField(blank=True, max_length=16384, null=True)),
                (
                    "temperature",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "wind_speed_kmh",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
                (
                    "cloud_cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.cloudcovercode",
                    ),
                ),
                (
                    "precipitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.precipitationcode",
                    ),
                ),
                (
                    "wind_direction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.winddirectioncode",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."weather_conditions"',
            },
        ),
        migrations.CreateModel(
            name="DraftWellEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "well_tag",
                    models.CharField(
                        db_comment="Identifier of a Registered Well",
                        default="Unset",
                        max_length=256,
                    ),
                ),
                (
                    "distance",
                    models.PositiveIntegerField(
                        db_comment="Distance from centroid of activity"
                    ),
                ),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."well_entries"',
            },
        ),
        migrations.AddIndex(
            model_name="draftactivity",
            index=models.Index(
                fields=["type", "date"], name="draft_activity_basic_date_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftactivity",
            index=models.Index(
                fields=["subtype", "date"], name="draft_activity_basic_date_sub_idx"
            ),
        ),
    ]
