# Generated by Django 6.0 on 2026-07-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_draftactivity_draftactivitydatarecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftactivity",
            name="computed_biogeoclimatic_zone",
            field=models.CharField(
                blank=True,
                db_comment="Large geographic area defined by similar regional climate (temperature, rainfall, moisture)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_elevation_m",
            field=models.SmallIntegerField(
                blank=True,
                db_comment="Estimated elevation of an area in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_fields_generated",
            field=models.BooleanField(
                db_column="computed_fields_generated",
                db_comment="Whether or not computed regional details have been generated",
                default=False,
            ),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_flrno_districts",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_invasive_plant_management_areas",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_moti_districts",
            field=models.CharField(
                blank=True,
                db_comment="Ministry of Transportation and Infrastructure (MOTI)",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_ownership",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="draftactivity",
            name="computed_regional_districts",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name="DraftRisoArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(db_index=True, max_length=62)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.draftactivitydatarecord",
                    ),
                ),
            ],
            options={
                "db_table": '"draft_activity"."riso_area"',
                "db_table_comment": "Regional Invasive Species Organization (RISO) areas",
                "abstract": False,
            },
        ),
    ]
