# Generated by Django 6.0.7 on 2026-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_chemplantentryaquatic_chemplantentryterrestrial_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemicaltreatmentaquaticinvasiveplantrecord",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentaquaticinvasiveplantrecord",
            name="invasive_plant",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentcalculationresultsperplantherbiciderecord",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentcalculationresultsperplantrecord",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentcalculationresultsrecord",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentdetails",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentdetails",
            name="chemical_application_method",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmenttankmix",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmenttankmixherbicide",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmenttankmixherbicide",
            name="granular_herbicide",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmenttankmixherbicide",
            name="herbicide_type",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmenttankmixherbicide",
            name="liquid_herbicide",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentterrestrialinvasiveplantrecord",
            name="activity_data_record",
        ),
        migrations.RemoveField(
            model_name="chemicaltreatmentterrestrialinvasiveplantrecord",
            name="invasive_plant",
        ),
        migrations.RemoveConstraint(
            model_name="herbicide",
            name="valid_calculation_type",
        ),
        migrations.AlterField(
            model_name="chemtreatmentcontext",
            name="calculation_type",
            field=models.CharField(choices=[("PAR", "PAR"), ("D", "D")]),
        ),
        migrations.AlterField(
            model_name="draftchemtreatmentcontext",
            name="calculation_type",
            field=models.CharField(
                blank=True, choices=[("PAR", "PAR"), ("D", "D")], null=True
            ),
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentAquaticInvasivePlantRecord",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentCalculationResultsPerPlantHerbicideRecord",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentCalculationResultsPerPlantRecord",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentCalculationResultsRecord",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentDetails",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentTankMix",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentTankMixHerbicide",
        ),
        migrations.DeleteModel(
            name="ChemicalTreatmentTerrestrialInvasivePlantRecord",
        ),
        migrations.DeleteModel(
            name="Herbicide",
        ),
    ]
