# Generated by Django 6.0.7 on 2026-07-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0028_remove_chemicaltreatmentaquaticinvasiveplantrecord_activity_data_record_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HerbicideCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."herbicide"',
                "db_table_comment": "All herbicide codes non-specific to type",
            },
        ),
        migrations.CreateModel(
            name="PlantCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("full", models.CharField(max_length=128)),
                ("code_sort_order", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateField(auto_now_add=True)),
                ("valid_to", models.DateField(default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": '"codes"."plant_code"',
                "db_table_comment": "All plant codes non-specific to type",
            },
        ),
        migrations.AlterField(
            model_name="chemicaltreatmentcontext",
            name="pesticide_employer_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.servicelicensenumberandcompany",
            ),
        ),
        migrations.AlterField(
            model_name="draftchemicaltreatmentcontext",
            name="pesticide_employer_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.servicelicensenumberandcompany",
            ),
        ),
        migrations.CreateModel(
            name="ChemicalApplicationCalculationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jurisdiction_percent", models.FloatField()),
                ("invasive_plant_percent", models.FloatField()),
                ("amount_of_mix_used", models.FloatField(blank=True, null=True)),
                ("area_treated_sqm", models.FloatField()),
                ("dilution", models.FloatField(blank=True, null=True)),
                (
                    "undiluted_herbicide_used_l",
                    models.FloatField(blank=True, null=True),
                ),
                ("percentage_area_covered", models.FloatField()),
                ("product_application_rate", models.FloatField(blank=True, null=True)),
                (
                    "activity_data_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.activitydatarecord",
                    ),
                ),
                (
                    "herbicide_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.herbicidetypecode",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.jurisdictioncode",
                    ),
                ),
                (
                    "herbicide_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.herbicidecode",
                    ),
                ),
                (
                    "invasive_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.plantcode"
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."chemical_calculation"',
                "db_table_comment": "Single result of a chemical calculation.",
            },
        ),
    ]
