# Generated by Django 6.0.7 on 2026-08-06 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_herbicidecode_plantcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityModificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        db_comment="Current version number of record", editable=False
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Date change occured"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Ios", "Ios"),
                            ("Android", "Android"),
                            ("Batch", "Batch"),
                            ("Web", "Web"),
                            ("Unknown", "Unknown"),
                        ]
                    ),
                ),
                (
                    "diff",
                    models.JSONField(
                        db_comment="Total changes between the previous version and the newest version"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.activity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="User who initiated the change",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"activity"."modification_record"',
                "db_table_comment": "Represents updates to a given activity record",
                "unique_together": {("version", "activity_id")},
            },
        ),
    ]
