# Generated by Django 6.0.7 on 2026-08-28 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_activitymodificationrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquaticplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="draftaquaticplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="draftterrestrialplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantmechanicaltreatmententry",
            name="disposed_material_amount",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
