# Generated by Django 6.0.7 on 2026-09-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0031_alter_aquaticplantmechanicaltreatmententry_disposed_material_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftterrestrialbiocontrolagentcountextended",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
