# Generated by Django 6.0.7 on 2026-09-15 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_alter_draftterrestrialbiocontrolagentcountextended_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="created_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="activity",
            name="received_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="aquaticplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("number of plants", "Number of plants"),
                    ("volume (m3)", "Volume (Cubic Meters)"),
                    ("weight", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="draftactivity",
            name="created_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="draftactivity",
            name="received_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="draftaquaticplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("number of plants", "Number of plants"),
                    ("volume (m3)", "Volume (Cubic Meters)"),
                    ("weight", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="draftterrestrialplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("number of plants", "Number of plants"),
                    ("volume (m3)", "Volume (Cubic Meters)"),
                    ("weight", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="terrestrialplantmechanicaltreatmententry",
            name="disposed_material_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("number of plants", "Number of plants"),
                    ("volume (m3)", "Volume (Cubic Meters)"),
                    ("weight", "Weight (kg)"),
                ],
                null=True,
            ),
        ),
    ]
