# Generated by Django 6.0.7 on 2026-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_biocontrolcollectionplant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="tidal_influence",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")]
            ),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="water_colour",
            field=models.CharField(blank=True, null=True),
        ),
    ]
