# Generated by Django 6.0.7 on 2026-09-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_observationplantaquatic_tidal_influence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="cloud_cover",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="precipitation",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="temperature_c",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="weather_comments",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatmentbiocontrolreleaseplant",
            name="wind_speed_kmh",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="cloud_cover",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="precipitation",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="temperature_c",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="wind_speed_kmh",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="cloud_cover",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="precipitation",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="temperature_c",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="wind_speed_kmh",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontrolreleaseplant",
            name="cloud_cover",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontrolreleaseplant",
            name="precipitation",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontrolreleaseplant",
            name="temperature_c",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontrolreleaseplant",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontrolreleaseplant",
            name="wind_speed_kmh",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentbiocontrolreleaseplant",
            name="collection_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
