# Generated by Django 6.0.7 on 2026-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_treatmentbiocontrolreleaseplant_cloud_cover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="collection_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="collection_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="end_time_collecting",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biocontrolcollectionplant",
            name="start_time_collecting",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="biocontrol_present",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="monitoring_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="monitoring_stop_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="monitoring_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringbiocontroldispersal",
            name="phenology_details_recorded",
            field=models.CharField(
                blank=True, choices=[("Yes", "Yes"), ("No", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="monitoringchemicalplant",
            name="invasive_plants_on_site",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringchemicalplant",
            name="management_efficacy",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringchemicalplant",
            name="treatment_evidence",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringmechanicalplant",
            name="invasive_plants_on_site",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringmechanicalplant",
            name="management_efficacy",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitoringmechanicalplant",
            name="treatment_evidence",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="has_voucher_specimen",
            field=models.CharField(
                blank=True, choices=[("Yes", "Yes"), ("No", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="pretreatment_observation",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="substrate_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="tidal_influence",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No"), ("Unknown", "Unknown")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="observationplantaquatic",
            name="waterbody_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="aspect",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="invasive_plant",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="observation_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="research_observation",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="slope_percent",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="specific_use",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="observationplantterrestrial",
            name="visible_well_nearby",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentbiocontrolreleaseplant",
            name="agent_mortality",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentbiocontrolreleaseplant",
            name="agent_source",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentbiocontrolreleaseplant",
            name="linear_segment",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="application_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="calculation_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="chemical_application_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="herbicide_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="herbicide_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="invasive_plant_percent_covered",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="service_license",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="temperature_c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="treatment_notice_signs",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantaquatic",
            name="wind_speed_kmh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="application_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="chemical_application_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="herbicide_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="herbicide_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="invasive_plant_percent_covered",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="service_license",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="tank_mix_used",
            field=models.CharField(
                blank=True, choices=[("Yes", "Yes"), ("No", "No")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="temperature_c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="treatment_notice_signs",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="wind_direction",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentchemicalplantterrestrial",
            name="wind_speed_kmh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantaquatic",
            name="disposal_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantaquatic",
            name="mechanical_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantaquatic",
            name="treated_area_sqm",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantterrestrial",
            name="disposal_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantterrestrial",
            name="mechanical_method",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="treatmentmechanicalplantterrestrial",
            name="treated_area_sqm",
            field=models.CharField(blank=True, null=True),
        ),
    ]
