# Generated by Django 6.0.7 on 2026-09-23 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_treatmentbiocontrolreleaseplant_cloud_cover_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # language=PostgreSQL
            sql="""
                create schema if not exists "teams";
            """,
            # language=PostgreSQL
            reverse_sql="""
                drop schema if exists "teams";
            """,
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "founding_date",
                    models.DateField(
                        auto_now_add=True,
                        db_comment="Date team was created. Deterministic for editable record",
                    ),
                ),
                (
                    "disbanded_date",
                    models.DateField(
                        blank=True,
                        db_comment="Date team was disbanded by the creator",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Display name for a team. What appears in the frontend",
                        max_length=64,
                    ),
                ),
                (
                    "agencies",
                    models.ManyToManyField(
                        db_table='"teams"."team_agencies"', to="api.fundingagencycode"
                    ),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"teams"."teams"',
                "db_table_comment": "Teams belonging to Data Managers for giving edit permission of cohorts",
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_stamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Pending",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.team"
                    ),
                ),
            ],
            options={
                "db_table": '"teams"."invitations"',
                "db_table_comment": "Invitations to join a given a team.",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "join_date",
                    models.DateField(
                        auto_now_add=True,
                        db_comment="Date user joined the team. Edit permissions begin here.",
                    ),
                ),
                (
                    "leave_date",
                    models.DateField(
                        blank=True,
                        db_comment="Date user left the team, Edit permissions end here.",
                        null=True,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        db_comment="Team that member belongs to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": '"teams"."member"',
            },
        ),
    ]
