# Generated by Django 6.0.7 on 2026-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_biocontrolcollectionplant_collection_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftterrestrialbiocontroldispersalmonitoringentry",
            name="historical_iapp_site",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringbiocontrolreleaseplant",
            name="historical_iapp_site",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="terrestrialbiocontroldispersalmonitoringentry",
            name="historical_iapp_site",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
