# Generated by Django 6.0.7 on 2026-10-08 17:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import csv, io, os, zipfile
from django.contrib.gis.geos import GEOSGeometry


def load_features_from_file(apps, schema_editor):
    Model = apps.get_model("api", "ZoneOfInterest")
    current_dir = os.path.dirname(__file__)
    file_path = os.path.abspath(os.path.join(current_dir, "seeds", "zoi_hex_grid.zip"))

    if not os.path.exists(file_path):
        raise FileNotFoundError(f"ZIP File not found at {file_path}")

    batch_size = 1000
    objects_to_create = []

    with zipfile.ZipFile(file_path, "r") as z:
        with z.open("zoi_hex_grid.csv", "r") as binary_file:
            text_file = io.TextIOWrapper(binary_file, encoding="utf-8")
            reader = csv.DictReader(text_file)

            for row in reader:
                wkt_str = row["geom"].strip()
                geom = GEOSGeometry(wkt_str, srid=3005)

                objects_to_create.append(Model(shape=geom))

                if len(objects_to_create) >= batch_size:
                    Model.objects.bulk_create(objects_to_create)
                    objects_to_create.clear()

            if objects_to_create:
                Model.objects.bulk_create(objects_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_team_teaminvitation_teammember"),
    ]

    operations = [
        migrations.RunSQL(
            # language=PostgreSQL
            sql="""
                create schema if not exists "mapping";
            """,
            # language=PostgreSQL
            reverse_sql="""
                drop schema if exists "mapping";
            """,
        ),
        migrations.CreateModel(
            name="ZoneOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "public_id",
                    models.GeneratedField(
                        db_comment="Public ID to differentiate from other IDs e.g. IAPP Sites",
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            models.Value("H"),
                            models.F("id"),
                            output_field=models.CharField(),
                        ),
                        output_field=models.CharField(max_length=32),
                        unique=True,
                    ),
                ),
                ("shape", django.contrib.gis.db.models.fields.GeometryField(srid=3005)),
            ],
            options={
                "db_table": '"mapping"."zone_of_interest_hex_grid"',
                "db_table_comment": "Hexagon Grid for defining Zones of Interest",
            },
        ),
        migrations.RunPython(
            load_features_from_file, reverse_code=migrations.RunPython.noop
        ),
    ]
