FROM node:16.14-alpine

# set variables
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY . .

RUN npm ci

CMD [ "npm", "run", "setup" ]
