FROM node:16.14-alpine
# set variables
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY . .

RUN npm ci

# run the database migrations only (no seeding)
CMD [ "npm", "run", "migrate:latest" ]
