/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ninja/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["api_protocol_activity_api_list_activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activity Search */
        post: operations["api_protocol_activity_api_activity_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity By Id */
        get: operations["api_protocol_activity_api_get_activity_by_id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMinimal
         * @description Minimal fields - shared between all representations
         */
        ActivityMinimal: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /** Short Id */
            short_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Type */
            type: string;
            /** Subtype */
            subtype: string;
        };
        /**
         * ActivitySearchParameters
         * @description An object representing activity search parameters
         */
        ActivitySearchParameters: {
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
        };
        /** ActivitySearchResult */
        ActivitySearchResult: {
            /** Items */
            items: components["schemas"]["ActivityMinimal"][];
            search: components["schemas"]["ActivitySearchParameters"];
        };
        /** ActivityOut */
        ActivityOut: {
            /** Batch Id */
            batch_id?: number | null;
            /** Batch Row Id */
            batch_row_id?: number | null;
            /** Area M */
            area_m?: number | null;
            /** Utm Zone */
            utm_zone?: number | null;
            /** Utm Easting */
            utm_easting?: number | null;
            /** Utm Northing */
            utm_northing?: number | null;
            /** Latitude */
            latitude?: string | null;
            /** Longitude */
            longitude?: string | null;
            /** Location Description */
            location_description?: string | null;
            /** Shape Radius */
            shape_radius?: string | null;
            /**
             * Creating Platform
             * @default Unknown
             */
            creating_platform: string;
            /**
             * Computed Fields Generated
             * @default false
             */
            computed_fields_generated: boolean;
            /** Computed Biogeoclimatic Zone */
            computed_biogeoclimatic_zone?: string | null;
            /** Computed Elevation M */
            computed_elevation_m?: number | null;
            /** Computed Flrno Districts */
            computed_flrno_districts?: string | null;
            /** Computed Invasive Plant Management Areas */
            computed_invasive_plant_management_areas?: string | null;
            /** Computed Moti Districts */
            computed_moti_districts?: string | null;
            /** Computed Ownership */
            computed_ownership?: string | null;
            /** Computed Regional Districts */
            computed_regional_districts?: string | null;
            /** Id */
            id?: string | null;
            /** Short Id */
            short_id: string;
            /** Type */
            type: string;
            /** Subtype */
            subtype: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Created By */
            created_by: string;
            /**
             * Form Status
             * @default Draft
             */
            form_status: string;
            /** Access Description */
            access_description?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Created Timestamp
             * Format: date-time
             */
            created_timestamp: string;
            /**
             * Received Timestamp
             * Format: date-time
             */
            received_timestamp: string;
            /** Linked Activities */
            linked_activities: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ActivityMinimal = components['schemas']['ActivityMinimal'];
export type ActivitySearchParameters = components['schemas']['ActivitySearchParameters'];
export type ActivitySearchResult = components['schemas']['ActivitySearchResult'];
export type ActivityOut = components['schemas']['ActivityOut'];
export type $defs = Record<string, never>;
export interface operations {
    api_protocol_activity_api_list_activities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityMinimal"][];
                };
            };
        };
    };
    api_protocol_activity_api_activity_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivitySearchParameters"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySearchResult"];
                };
            };
        };
    };
    api_protocol_activity_api_get_activity_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityOut"];
                };
            };
        };
    };
}
