export const AUTH_REQUEST_COMPLETE = 'AUTH_REQUEST_COMPLETE';
export const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
export const AUTH_INITIALIZE_REQUEST = 'AUTH_INITIALIZE_REQUEST';
export const AUTH_INITIALIZE_COMPLETE = 'AUTH_INITIALIZE_COMPLETE';
export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_SIGNOUT_REQUEST = 'AUTH_SIGNOUT_REQUEST';
export const AUTH_SIGNOUT_COMPLETE = 'AUTH_SIGNOUT_COMPLETE';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const AUTH_UPDATE_TOKEN_STATE = 'AUTH_UPDATE_TOKEN_STATE';
export const AUTH_REFRESH_ROLES_REQUEST = 'AUTH_REFRESH_ROLES_REQUEST';
export const AUTH_CLEAR_ROLES = 'AUTH_CLEAR_ROLES';
export const AUTH_REFRESH_ROLES_ERROR = 'AUTH_REFRESH_ROLES_ERROR';
export const AUTH_REFRESH_ROLES_COMPLETE = 'AUTH_REFRESH_ROLES_COMPLETE';

export const USERINFO_LOAD_COMPLETE = 'USERINFO_LOAD_COMPLETE';
export const USERINFO_CLEAR_REQUEST = 'USERINFO_CLEAR_REQUEST';

export const NETWORK_GO_ONLINE = 'NETWORK_GO_ONLINE';
export const NETWORK_GO_OFFLINE = 'NETWORK_GO_OFFLINE';

export const ACTIVITY_GET_INITIAL_STATE_REQUEST = 'ACTIVITY_GET_INITIAL_STATE_REQUEST';
export const ACTIVITY_GET_INITIAL_STATE_SUCCESS = 'ACTIVITY_GET_INITIAL_STATE_SUCCESS';
export const ACTIVITY_GET_INITIAL_STATE_FAILURE = 'ACTIVITY_GET_INITIAL_STATE_FAILURE';

export const ACTIVITY_GET_REQUEST = 'ACTIVITY_GET_REQUEST';
export const ACTIVITY_GET_NETWORK_REQUEST = 'ACTIVITY_GET_NETWORK_REQUEST';
export const ACTIVITY_GET_LOCALDB_REQUEST = 'ACTIVITY_GET_LOCALDB_REQUEST';
export const ACTIVITY_GET_SUCCESS = 'ACTIVITY_GET_SUCCESS';
export const ACTIVITY_GET_FAILURE = 'ACTIVITY_GET_FAILURE';

export const ACTIVITY_UPDATE_GEO_REQUEST = 'ACTIVITY_UPDATE_GEO_REQUEST';
export const ACTIVITY_UPDATE_GEO_SUCCESS = 'ACTIVITY_UPDATE_GEO_SUCCESS';
export const ACTIVITY_UPDATE_GEO_FAILURE = 'ACTIVITY_UPDATE_GEO_FAILURE';

export const ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST = 'ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST';
export const ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST_ONLINE =
  'ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST_ONLINE';
export const ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST_OFFLINE =
  'ACTIVITY_GET_SUGGESTED_JURISDICTIONS_REQUEST_OFFLINE';
export const ACTIVITY_GET_SUGGESTED_JURISDICTIONS_SUCCESS = 'ACTIVITY_GET_SUGGESTED_JURISDICTIONS_SUCCESS';

export const ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST = 'ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST';
export const ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST_ONLINE = 'ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST_ONLINE';
export const ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST_OFFLINE = 'ACTIVITY_GET_SUGGESTED_PERSONS_REQUEST_OFFLINE';
export const ACTIVITY_GET_SUGGESTED_PERSONS_SUCCESS = 'ACTIVITY_GET_SUGGESTED_PERSONS_SUCCESS';

export const ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST = 'ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST';
export const ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST_ONLINE = 'ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST_ONLINE';
export const ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST_OFFLINE = 'ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_REQUEST_OFFLINE';
export const ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_SUCCESS = 'ACTIVITY_GET_SUGGESTED_TREATMENT_IDS_SUCCESS';

export const ACTIVITY_ON_FORM_CHANGE_REQUEST = 'ACTIVITY_ON_FORM_CHANGE_REQUEST';
export const ACTIVITY_ON_FORM_CHANGE_SUCCESS = 'ACTIVITY_ON_FORM_CHANGE_SUCCESS';

export const ACTIVITY_CHEM_TREATMENT_DETAILS_FORM_ON_CHANGE_REQUEST =
  'ACTIVITY_CHEM_TREATMENT_DETAILS_FORM_ON_CHANGE_REQUEST';
export const ACTIVITY_CHEM_TREATMENT_DETAILS_FORM_ON_CHANGE_SUCCESS =
  'ACTIVITY_CHEM_TREATMENT_DETAILS_FORM_ON_CHANGE_SUCCESS';

export const ACTIVITY_UPDATE_AUTOFILL_REQUEST = 'ACTIVITY_UPDATE_AUTOFILL_REQUEST';
export const ACTIVITY_UPDATE_AUTOFILL_SUCCESS = 'ACTIVITY_UPDATE_AUTOFILL_SUCCESS';
export const ACTIVITY_UPDATE_AUTOFILL_FAILURE = 'ACTIVITY_UPDATE_AUTOFILL_FAILURE';
export const ACTIVITY_UPDATE_PHOTO_REQUEST = 'ACTIVITY_UPDATE_PHOTO_REQUEST';
export const ACTIVITY_UPDATE_PHOTO_SUCCESS = 'ACTIVITY_UPDATE_PHOTO_SUCCESS';
export const ACTIVITY_UPDATE_PHOTO_FAILURE = 'ACTIVITY_UPDATE_PHOTO_FAILURE';
export const ACTIVITY_LINK_RECORD_REQUEST = 'ACTIVITY_LINK_RECORD_REQUEST';
export const ACTIVITY_LINK_RECORD_SUCCESS = 'ACTIVITY_LINK_RECORD_SUCCESS';
export const ACTIVITY_LINK_RECORD_FAILURE = 'ACTIVITY_LINK_RECORD_FAILURE';
export const ACTIVITY_PERSIST_REQUEST = 'ACTIVITY_PERSIST_REQUEST';
export const ACTIVITY_PERSIST_SUCCESS = 'ACTIVITY_PERSIST_SUCCESS';
export const ACTIVITY_PERSIST_FAILURE = 'ACTIVITY_PERSIST_FAILURE';

export const ACTIVITY_SAVE_REQUEST = 'ACTIVITY_SAVE_REQUEST';
export const ACTIVITY_SAVE_SUCCESS = 'ACTIVITY_SAVE_SUCCESS';
export const ACTIVITY_SAVE_FAILURE = 'ACTIVITY_SAVE_FAILURE';

export const ACTIVITY_SAVE_NETWORK_REQUEST = 'ACTIVITY_SAVE__NETWORK_REQUEST';
export const ACTIVITY_SAVE_NETWORK_SUCCESS = 'ACTIVITY_SAVE__NETWORK_SUCCESS';
export const ACTIVITY_SAVE_NETWORK_FAILURE = 'ACTIVITY_SAVE__NETWORK_FAILURE';

export const ACTIVITY_CREATE_REQUEST = 'ACTIVITY_CREATE_REQUEST';
export const ACTIVITY_CREATE_NETWORK = 'ACTIVITY_CREATE_NETWORK';
export const ACTIVITY_CREATE_LOCAL = 'ACTIVITY_CREATE_LOCAL';
export const ACTIVITY_CREATE_SUCCESS = 'ACTIVITY_CREATE_SUCCESS';
export const ACTIVITY_CREATE_FAILURE = 'ACTIVITY_CREATE_FAILURE';

export const ACTIVITY_SUBMIT_REQUEST = 'ACTIVITY_SUBMIT_REQUEST';
export const ACTIVITY_SUBMIT_SUCCESS = 'ACTIVITY_SUBMIT_SUCCESS';
export const ACTIVITY_SUBMIT_FAILURE = 'ACTIVITY_SUBMIT_FAILURE';
export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST';
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS';
export const ACTIVITY_DELETE_FAILURE = 'ACTIVITY_DELETE_FAILURE';
export const ACTIVITY_SET_ACTIVE_REQUEST = 'ACTIVITY_SET_ACTIVE_REQUEST';
export const ACTIVITY_SET_ACTIVE_SUCCESS = 'ACTIVITY_SET_ACTIVE_SUCCESS';
export const ACTIVITY_SET_ACTIVE_FAILURE = 'ACTIVITY_SET_ACTIVE_FAILURE';

export const ACTIVITY_ADD_PHOTO_REQUEST = 'ACTIVITY_ADD_PHOTO_REQUEST';
export const ACTIVITY_ADD_PHOTO_SUCCESS = 'ACTIVITY_ADD_PHOTO_SUCCESS';
export const ACTIVITY_ADD_PHOTO_FAILURE = 'ACTIVITY_ADD_PHOTO_FAILURE';
export const ACTIVITY_DELETE_PHOTO_REQUEST = 'ACTIVITY_DELETE_PHOTO_REQUEST';
export const ACTIVITY_DELETE_PHOTO_SUCCESS = 'ACTIVITY_DELETE_PHOTO_SUCCESS';
export const ACTIVITY_DELETE_PHOTO_FAILURE = 'ACTIVITY_DELETE_PHOTO_FAILURE';
export const ACTIVITY_EDIT_PHOTO_REQUEST = 'ACTIVITY_EDIT_PHOTO_REQUEST';
export const ACTIVITY_EDIT_PHOTO_SUCCESS = 'ACTIVITY_EDIT_PHOTO_SUCCESS';
export const ACTIVITY_EDIT_PHOTO_FAILURE = 'ACTIVITY_EDIT_PHOTO_FAILURE';

// NewRecordDialog.tsx selectors
export const USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_REQUEST = 'USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_REQUEST';
export const USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_SUCCESS = 'USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_SUCCESS';
export const USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_FAILURE = 'USER_SETTINGS_SET_NEW_RECORD_DIALOG_STATE_FAILURE';

export const USER_SETTINGS_GET_INITIAL_STATE_REQUEST = 'USER_SETTINGS_GET_INITIAL_STATE_REQUEST';
export const USER_SETTINGS_GET_INITIAL_STATE_SUCCESS = 'USER_SETTINGS_GET_INITIAL_STATE_SUCCESS';
export const USER_SETTINGS_GET_INITIAL_STATE_FAILURE = 'USER_SETTINGS_GET_INITIAL_STATE_FAILURE';
export const USER_SETTINGS_SET_ACTIVE_ACTIVITY_REQUEST = 'USER_SETTINGS_SET_ACTIVE_ACTIVITY_REQUEST';
export const USER_SETTINGS_SET_ACTIVE_ACTIVITY_SUCCESS = 'USER_SETTINGS_SET_ACTIVE_ACTIVITY_SUCCESS';
export const USER_SETTINGS_SET_ACTIVE_ACTIVITY_FAILURE = 'USER_SETTINGS_SET_ACTIVE_ACTIVITY_FAILURE';
export const USER_SETTINGS_SET_ACTIVE_IAPP_REQUEST = 'USER_SETTINGS_SET_ACTIVE_IAPP_REQUEST';
export const USER_SETTINGS_SET_ACTIVE_IAPP_SUCCESS = 'USER_SETTINGS_SET_ACTIVE_IAPP_SUCCESS';
export const USER_SETTINGS_SET_ACTIVE_IAPP_FAILURE = 'USER_SETTINGS_SET_ACTIVE_IAPP_FAILURE';

export const ACTIVITY_DEBUG = 'ACTIVITY_DEBUG';

export const USER_SETTINGS_ADD_RECORD_SET_REQUEST = 'USER_SETTINGS_ADD_RECORD_SET_REQUEST';
export const USER_SETTINGS_ADD_RECORD_SET_SUCCESS = 'USER_SETTINGS_ADD_RECORD_SET_SUCCESS';
export const USER_SETTINGS_ADD_RECORD_SET_FAILURE = 'USER_SETTINGS_ADD_RECORD_SET_FAILURE';
export const USER_SETTINGS_REMOVE_RECORD_SET_REQUEST = 'USER_SETTINGS_REMOVE_RECORD_SET_REQUEST';
export const USER_SETTINGS_REMOVE_RECORD_SET_SUCCESS = 'USER_SETTINGS_REMOVE_RECORD_SET_SUCCESS';
export const USER_SETTINGS_REMOVE_RECORD_SET_FAILURE = 'USER_SETTINGS_REMOVE_RECORD_SET_FAILURE';
export const USER_SETTINGS_SET_SELECTED_RECORD_REQUEST = 'USER_SETTINGS_SET_SELECTED_RECORD_REQUEST';
export const USER_SETTINGS_SET_BOUNDARIES_REQUEST = 'USER_SETTINGS_SET_BOUNDARIES_REQUEST';
export const USER_SETTINGS_SET_BOUNDARIES_SUCCESS = 'USER_SETTINGS_SET_BOUNDARIES_SUCCESS';
export const USER_SETTINGS_SET_BOUNDARIES_FAILURE = 'USER_SETTINGS_SET_BOUNDARIES_FAILURE';
export const USER_SETTINGS_DELETE_BOUNDARY_REQUEST = 'USER_SETTINGS_DELETE_BOUNDARY_REQUEST';
export const USER_SETTINGS_DELETE_BOUNDARY_SUCCESS = 'USER_SETTINGS_DELETE_BOUNDARY_SUCCESS';
export const USER_SETTINGS_DELETE_BOUNDARY_FAILURE = 'USER_SETTINGS_DELETE_BOUNDARY_FAILURE';
export const USER_SETTINGS_DELETE_KML_REQUEST = 'USER_SETTINGS_DELETE_KML_REQUEST';
export const USER_SETTINGS_DELETE_KML_SUCCESS = 'USER_SETTINGS_DELETE_KML_SUCCESS';
export const USER_SETTINGS_DELETE_KML_FAILURE = 'USER_SETTINGS_DELETE_KML_FAILURE';
export const USER_SETTINGS_ADD_BOUNDARY_TO_SET_REQUEST = 'USER_SETTINGS_ADD_BOUNDARY_TO_SET_REQUEST';
export const USER_SETTINGS_ADD_BOUNDARY_TO_SET_SUCCESS = 'USER_SETTINGS_ADD_BOUNDARY_TO_SET_SUCCESS';
export const USER_SETTINGS_ADD_BOUNDARY_TO_SET_FAILURE = 'USER_SETTINGS_ADD_BOUNDARY_TO_SET_FAILURE';
export const USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_REQUEST = 'USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_REQUEST';
export const USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_SUCCESS = 'USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_SUCCESS';
export const USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_FAILURE = 'USER_SETTINGS_REMOVE_BOUNDARY_FROM_SET_FAILURE';
export const USER_SETTINGS_SET_RECORD_SET_REQUEST = 'USER_SETTINGS_SET_RECORD_SET_REQUEST';
export const USER_SETTINGS_SET_RECORD_SET_SUCCESS = 'USER_SETTINGS_SET_RECORD_SET_SUCCESS';
export const USER_SETTINGS_SET_RECORD_SET_FAILURE = 'USER_SETTINGS_SET_RECORD_SET_FAILURE';
export const USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_REQUEST = 'USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_REQUEST';
export const USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_SUCCESS = 'USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_SUCCESS';
export const USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_FAILURE = 'USER_SETTINGS_TOGGLE_RECORDS_EXPANDED_FAILURE';
export const USER_SETTINGS_SET_DARK_THEME = 'USER_SETTINGS_SET_DARK_THEME';
export const USER_SETTINGS_SET_MAP_CENTER_REQUEST = 'USER_SETTINGS_SET_MAP_CENTER_REQUEST';
export const USER_SETTINGS_SET_MAP_CENTER_SUCCESS = 'USER_SETTINGS_SET_MAP_CENTER_SUCCESS';
export const USER_SETTINGS_SET_MAP_CENTER_FAILURE = 'USER_SETTINGS_SET_MAP_CENTER_FAILURE';

// Tabs
export const TABS_GET_INITIAL_STATE_REQUEST = 'TABS_GET_INITIAL_STATE_REQUEST';
export const TABS_GET_INITIAL_STATE_SUCCESS = 'TABS_GET_INITIAL_STATE_SUCCESS';
export const TABS_GET_INITIAL_STATE_FAILURE = 'TABS_GET_INITIAL_STATE_FAILURE';
export const TABS_SET_ACTIVE_TAB_REQUEST = 'TABS_SET_ACTIVE_TAB_REQUEST';
export const TABS_SET_ACTIVE_TAB_SUCCESS = 'TABS_SET_ACTIVE_TAB_SUCCESS';
export const TABS_SET_ACTIVE_TAB_FAILURE = 'TABS_SET_ACTIVE_TAB_FAILURE';

export const ACTIVITIES_GEOJSON_GET_REQUEST = 'ACTIVITIES_GEOJSON_GET_REQUEST';
export const ACTIVITIES_GEOJSON_GET_ONLINE = 'ACTIVITIES_GEOJSON_GET_ONLINE';
export const ACTIVITIES_GEOJSON_GET_OFFLINE = 'ACTIVITIES_GEOJSON_GET_OFFLINE';
export const ACTIVITIES_GEOJSON_GET_SUCCESS = 'ACTIVITIES_GEOJSON_GET_SUCCESS';

export const IAPP_GET_REQUEST = 'IAPP_GET_REQUEST';
export const IAPP_GET_LOCALDB_REQUEST = 'IAPP_GET_LOCALDB';
export const IAPP_GET_NETWORK_REQUEST = 'IAPP_GET_ONLINE';
export const IAPP_GET_SUCCESS = 'IAPP_GET_SUCCESS';
export const IAPP_GET_FAILURE = 'IAPP_GET_FAILURE';

export const IAPP_GEOJSON_GET_REQUEST = 'IAPP_GEOJSON_GET_REQUEST';
export const IAPP_GEOJSON_GET_ONLINE = 'IAPP_GEOJSON_GET_ONLINE';
export const IAPP_GEOJSON_GET_OFFLINE = 'IAPP_GEOJSON_GET_OFFLINE';
export const IAPP_GEOJSON_GET_SUCCESS = 'IAPP_GEOJSON_GET_SUCCESS';

export const IAPP_INIT_LAYER_STATE_REQUEST = 'IAPP_INIT_LAYER_STATE_REQUEST';
export const IAPP_INIT_LAYER_STATE_SUCCESS = 'IAPP_INIT_LAYER_STATE_SUCCESS';

export const IAPP_TABLE_ROWS_GET_REQUEST = 'IAPP_TABLE_ROWS_GET_REQUEST';
export const IAPP_TABLE_ROWS_GET_ONLINE = 'IAPP_TABLE_ROWS_GET_ONLINE';
export const IAPP_TABLE_ROWS_GET_OFFLINE = 'IAPP_TABLE_ROWS_GET_OFFLINE';
export const IAPP_TABLE_ROWS_GET_SUCCESS = 'IAPP_TABLE_ROWS_GET_SUCCESS';
export const IAPP_TABLE_ROWS_GET_FAILURE = 'IAPP_TABLE_ROWS_GET_FAILURE';

export const IAPP_RECORDSET_ID_LIST_GET_SUCCESS = 'IAPP_RECORDSET_ID_LIST_GET_SUCCESS';

export const ACTIVITIES_TABLE_ROWS_GET_REQUEST = 'ACTIVITIES_TABLE_ROWS_GET_REQUEST';
export const ACTIVITIES_TABLE_ROWS_GET_ONLINE = 'ACTIVITIES_TABLE_ROWS_GET_ONLINE';
export const ACTIVITIES_TABLE_ROWS_GET_OFFLINE = 'ACTIVITIES_TABLE_ROWS_GET_OFFLINE';
export const ACTIVITIES_TABLE_ROWS_GET_SUCCESS = 'ACTIVITIES_TABLE_ROWS_GET_SUCCESS';
export const ACTIVITIES_TABLE_ROWS_GET_FAILURE = 'ACTIVITIES_TABLE_ROWS_GET_FAILURE';

export const MAP_INIT_REQUEST = 'MAP_INIT_REQUEST';
export const MAP_INIT_SUCCESS = 'MAP_INIT_SUCCESS';

export const MAP_TOGGLE_BASEMAP = 'MAP_TOGGLE_BASEMAP';
export const MAP_TOGGLE_HD = 'MAP_TOGGLE_HD';
export const MAP_TOGGLE_ACCURACY = 'MAP_TOGGLE_ACCURACY';
export const MAP_TOGGLE_TRACKING = 'MAP_TOGGLE_TRACKING';
export const MAP_TOGGLE_PANNED = 'MAP_TOGGLE_PANNED';
export const MAP_SET_COORDS = 'MAP_SET_COORDS';
export const LEAFLET_SET_WHOS_EDITING = 'LEAFLET_SET_WHOS_EDITING';
export const TOGGLE_BASIC_PICKER_LAYER = 'TOGGLE_BASIC_PICKER_LAYER';

//whats here tool
export const MAP_TOGGLE_WHATS_HERE = 'MAP_TOGGLE_WHATS_HERE';
export const MAP_WHATS_HERE_FEATURE = 'MAP_WHATS_HERE_FEATURE';
export const MAP_WHATS_HERE_INIT_GET_POI = 'MAP_WHATS_HERE_INIT_GET_POI';
export const WHATS_HERE_PAGE_POI = 'WHATS_HERE_PAGE_POI';
export const WHATS_HERE_IAPP_ROWS_REQUEST = 'WHATS_HERE_IAPP_ROWS_REQUEST';
export const WHATS_HERE_IAPP_ROWS_ONLINE = 'WHATS_HERE_IAPP_ROWS_ONLINE';
export const WHATS_HERE_IAPP_ROWS_OFFLINE = 'WHATS_HERE_IAPP_ROWS_OFFLINE';
export const WHATS_HERE_IAPP_ROWS_SUCCESS = 'WHATS_HERE_IAPP_ROWS_SUCCESS';

export const WHATS_HERE_PAGE_ACTIVITY = 'WHATS_HERE_PAGE_ACTIVITY';
export const MAP_WHATS_HERE_INIT_GET_ACTIVITIES = 'MAP_WHATS_HERE_INIT_GET_ACTIVITIES';
export const WHATS_HERE_ACTIVITY_ROWS_REQUEST = 'WHATS_HERE_ACTIVITY_ROWS_REQUEST';
export const WHATS_HERE_ACTIVITY_ROWS_ONLINE = 'WHATS_HERE_ACTIVITY_ROWS_ONLINE';
export const WHATS_HERE_ACTIVITY_ROWS_OFFLINE = 'WHATS_HERE_ACTIVITY_ROWS_OFFLINE';
export const WHATS_HERE_ACTIVITY_ROWS_SUCCESS = 'WHATS_HERE_ACTIVITY_ROWS_SUCCESS';

export const MAP_DELETE_LAYER_AND_TABLE = 'MAP_DELETE_LAYER_AND_TABLE';

export const LAYER_STATE_UPDATE = 'LAYER_STATE_UPDATE';
export const FILTER_STATE_UPDATE = 'FILTER_STATE_UPDATE';
export const PAGE_OR_LIMIT_UPDATE = 'PAGE_OR_LIMIT_CHANGE';
export const SORT_COLUMN_STATE_UPDATE = 'SORT_COLUMN_STATE_UPDATE';

export const IAPP_GET_IDS_FOR_RECORDSET_REQUEST = 'IAPP_GET_IDS_FOR_RECORDSET_REQUEST';
export const IAPP_GET_IDS_FOR_RECORDSET_ONLINE = 'IAPP_GET_IDS_FOR_RECORDSET_ONLINE';
export const IAPP_GET_IDS_FOR_RECORDSET_OFFLINE = 'IAPP_GET_IDS_FOR_RECORDSET_OFFLINE';
export const IAPP_GET_IDS_FOR_RECORDSET_SUCCESS = 'IAPP_GET_IDS_FOR_RECORDSET_SUCCESS';

export const ACTIVITIES_GET_IDS_FOR_RECORDSET_REQUEST = 'ACTIVITIES_GET_IDS_FOR_RECORDSET_REQUEST';
export const ACTIVITIES_GET_IDS_FOR_RECORDSET_ONLINE = 'ACTIVITIES_GET_IDS_FOR_RECORDSET_ONLINE';
export const ACTIVITIES_GET_IDS_FOR_RECORDSET_OFFLINE = 'ACTIVITIES_GET_IDS_FOR_RECORDSET_OFFLINE';
export const ACTIVITIES_GET_IDS_FOR_RECORDSET_SUCCESS = 'ACTIVITIES_GET_IDS_FOR_RECORDSET_SUCCESS';
