export const AUTH_REQUEST_COMPLETE = 'AUTH_REQUEST_COMPLETE';
export const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
export const AUTH_INITIALIZE_REQUEST = 'AUTH_INITIALIZE_REQUEST';
export const AUTH_INITIALIZE_COMPLETE = 'AUTH_INITIALIZE_COMPLETE';
export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const AUTH_UPDATE_TOKEN_STATE = 'AUTH_UPDATE_TOKEN_STATE';
export const AUTH_REFRESH_ROLES_REQUEST = 'AUTH_REFRESH_ROLES_REQUEST';
export const AUTH_CLEAR_ROLES = 'AUTH_CLEAR_ROLES';
export const AUTH_REFRESH_ROLES_ERROR = 'AUTH_REFRESH_ROLES_ERROR';
export const AUTH_REFRESH_ROLES_COMPLETE = 'AUTH_REFRESH_ROLES_COMPLETE';


export const TEST_GENERATION_LOCK_REQUEST = 'TEST_GENERATION_LOCK_REQUEST';
export const TEST_GENERATION_LOCK_COMPLETE = 'TEST_GENERATION_LOCK_COMPLETE';
export const GENERATION_LOCK_ERROR = 'GENERATION_LOCK_ERROR';
export const ACQUIRE_GENERATION_LOCK_REQUEST = 'ACQUIRE_GENERATION_LOCK_REQUEST';
export const ACQUIRE_GENERATION_LOCK_COMPLETE = 'ACQUIRE_GENERATION_LOCK_COMPLETE';
export const RENEW_GENERATION_LOCK_REQUEST = 'RENEW_GENERATION_LOCK_REQUEST';
export const RENEW_GENERATION_LOCK_COMPLETE = 'RENEW_GENERATION_LOCK_COMPLETE';
export const RELEASE_GENERATION_LOCK_REQUEST = 'RELEASE_GENERATION_LOCK_REQUEST';
export const RELEASE_GENERATION_LOCK_COMPLETE = 'RELEASE_GENERATION_LOCK_COMPLETE';

