export enum TargetMode {
  DISABLED = 'DISABLED',
  GENERIC = 'GENERIC',
  WHATS_HERE = 'WHATS_HERE',
  CUSTOM_LAYER = 'CUSTOM_LAYER',
  ACTIVITY = 'ACTIVITY',
  ACTIVITY_GEO_TRACK = 'ACTIVITY_GEO_TRACK',
  TRIP_PLANNING = 'TRIP_PLANNING'
}
