export enum TargetMode {
  DISABLED = 'DISABLED',
  GENERIC = 'GENERIC',
  WHATS_HERE = 'WHATS_HERE',
  CUSTOM_LAYER = 'CUSTOM_LAYER',
  LEGACY_FORM = 'LEGACY_FORM',
  ACTIVITY_GEO_TRACK = 'ACTIVITY_GEO_TRACK',
  TRIP_PLANNING = 'TRIP_PLANNING',
  ACTIVITY_FORM = 'ACTIVITY'
}
