export const ACTIVITY_GET_INITIAL_STATE_REQUEST = 'ACTIVITY_GET_INITIAL_STATE_REQUEST';
export const ACTIVITY_GET_INITIAL_STATE_SUCCESS = 'ACTIVITY_GET_INITIAL_STATE_SUCCESS';
export const ACTIVITY_GET_INITIAL_STATE_FAILURE = 'ACTIVITY_GET_INITIAL_STATE_FAILURE';

export const ACTIVITY_UPDATE_GEO_REQUEST = 'ACTIVITY_UPDATE_GEO_REQUEST';
export const ACTIVITY_UPDATE_GEO_SUCCESS = 'ACTIVITY_UPDATE_GEO_SUCCESS';

export const ACTIVITY_BUILD_SCHEMA_FOR_FORM_REQUEST = 'ACTIVITY_BUILD_SCHEMA_FOR_FORM_REQUEST';
export const ACTIVITY_BUILD_SCHEMA_FOR_FORM_SUCCESS = 'ACTIVITY_BUILD_SCHEMA_FOR_FORM_SUCCESS';

export const ACTIVITY_ON_FORM_CHANGE_REQUEST = 'ACTIVITY_ON_FORM_CHANGE_REQUEST';
export const ACTIVITY_ON_FORM_CHANGE_SUCCESS = 'ACTIVITY_ON_FORM_CHANGE_SUCCESS';

export const ACTIVITY_SET_CURRENT_HASH_REQUEST = 'ACTIVITY_SET_CURRENT_HASH_REQUEST';
export const ACTIVITY_SET_CURRENT_HASH_SUCCESS = 'ACTIVITY_SET_CURRENT_HASH_SUCCESS';
export const ACTIVITY_SET_CURRENT_HASH_FAILURE = 'ACTIVITY_SET_CURRENT_HASH_REQUEST';

export const TOGGLE_CUSTOMIZE_LAYERS = 'TOGGLE_CUSTOMIZE_LAYERS';

export const ACTIVITY_SAVE_OFFLINE = 'ACTIVITY_SAVE_OFFLINE';
export const ACTIVITY_RESTORE_OFFLINE = 'ACTIVITY_RESTORE_OFFLINE';
export const ACTIVITY_OFFLINE_DELETE_ITEM = 'ACTIVITY_OFFLINE_DELETE_ITEM';
export const ACTIVITY_UPDATE_SYNC_STATE = 'ACTIVITY_UPDATE_SYNC_STATE';
export const ACTIVITY_OFFLINE_SYNC_DIALOG_SET_STATE = 'ACTIVITY_OFFLINE_SYNC_DIALOG_SET_STATE';

export const ACTIVITY_RUN_OFFLINE_SYNC = 'ACTIVITY_RUN_OFFLINE_SYNC';
export const ACTIVITY_RUN_OFFLINE_SYNC_COMPLETE = 'ACTIVITY_RUN_OFFLINE_SYNC_COMPLETE';

export const PAN_AND_ZOOM_TO_ACTIVITY = 'PAN_AND_ZOOM_TO_ACTIVITY';

export const RECORDSET_SET_SORT = 'RECORDSET_SET_SORT';

export const IAPP_PAN_AND_ZOOM = 'IAPP_PAN_AND_ZOOM';

export const MAP_SET_COORDS = 'MAP_SET_COORDS';
export const TOGGLE_BASIC_PICKER_LAYER = 'TOGGLE_BASIC_PICKER_LAYER';
export const RECORD_SET_TO_EXCEL_REQUEST = 'RECORD_SET_TO_EXCEL_REQUEST';
export const RECORD_SET_TO_EXCEL_SUCCESS = 'RECORD_SET_TO_EXCEL_SUCCESS';
export const RECORD_SET_TO_EXCEL_FAILURE = 'RECORD_SET_TO_EXCEL_FAILURE';
export const MAP_LABEL_EXTENT_FILTER_REQUEST = 'MAP_LABEL_EXTENT_FILTER_REQUEST';
export const MAP_LABEL_EXTENT_FILTER_SUCCESS = 'MAP_LABEL_EXTENT_FILTER_SUCCESS';
export const IAPP_EXTENT_FILTER_REQUEST = 'IAPP_EXTENT_FILTER_REQUEST';
export const IAPP_EXTENT_FILTER_SUCCESS = 'IAPP_EXTENT_FILTER_SUCCESS';
export const SET_TOO_MANY_LABELS_DIALOG = 'SET_TOO_MANY_LABELS_DIALOG';

export const TOGGLE_WMS_LAYER = 'TOGGLE_WMS_LAYER';
export const TOGGLE_LAYER_PICKER_OPEN = 'TOGGLE_LAYER_PICKER_OPEN';

export const MAP_ON_SHAPE_CREATE = 'MAP_ON_SHAPE_CREATE';
export const MAP_ON_SHAPE_UPDATE = 'MAP_ON_SHAPE_UPDATE';
export const MAIN_MAP_MOVE = 'MAIN_MAP_MOVE';
export const ACTIVITY_PAGE_MAP_EXTENT_TOGGLE = 'ACTIVITY_PAGE_MAP_EXTENT_TOGGLE';

export const MAP_DELETE_LAYER_AND_TABLE = 'MAP_DELETE_LAYER_AND_TABLE';

export const PAGE_OR_LIMIT_UPDATE = 'PAGE_OR_LIMIT_CHANGE';

export const FILTERS_PREPPED_FOR_VECTOR_ENDPOINT = 'FILTERS_PREPPED_FOR_VECTOR_ENDPOINT';
export const FILTER_PREP_FOR_VECTOR_ENDPOINT = 'FILTER_PREP_FOR_VECTOR_ENDPOINT';

export const REMOVE_SERVER_BOUNDARY = 'REMOVE_SERVER_BOUNDARY';

export const CSV_LINK_CLICKED = 'CSV_LINK_CLICKED';

export const EXPORT_CONFIG_LOAD_REQUEST = 'EXPORT_CONFIG_LOAD_REQUEST';
export const EXPORT_CONFIG_LOAD_ERROR = 'EXPORT_CONFIG_LOAD_ERROR';
export const EXPORT_CONFIG_LOAD_SUCCESS = 'EXPORT_CONFIG_LOAD_SUCCESS';

export const TRAINING_VIDEOS_LIST_REQUEST = 'TRAINING_VIDEOS_LIST_REQUEST';
export const TRAINING_VIDEOS_LIST_REQUEST_COMPLETE = 'TRAINING_VIDEOS_LIST_REQUEST_COMPLETE';

export const EMAIL_SETTINGS_UPDATE = 'EMAIL_SETTINGS_REQUEST';
export const EMAIL_SETTINGS_UPDATE_SUCCESS = 'EMAIL_SETTINGS_UPDATE_SUCCESS';
export const EMAIL_SETTINGS_UPDATE_FAILURE = 'EMAIL_SETTINGS_UPDATE_FAILURE';

export const EMAIL_SETTINGS_RETRIEVE_REQUEST = 'EMAIL_SETTINGS_RETRIEVE_REQUEST';
export const EMAIL_SETTINGS_RETRIEVE_REQUEST_SUCCESS = 'EMAIL_SETTINGS_RETRIEVE_REQUEST_SUCCESS';

export const EMAIL_TEMPLATES_UPDATE = 'EMAIL_TEMPLATES_REQUEST';
export const EMAIL_TEMPLATES_UPDATE_SUCCESS = 'EMAIL_TEMPLATES_UPDATE_SUCCESS';
export const EMAIL_TEMPLATES_UPDATE_FAILURE = 'EMAIL_TEMPLATES_UPDATE_FAILURE';
export const EMAIL_TEMPLATES_SET_ACTIVE = 'EMAIL_TEMPLATES_SET_ACTIVE';

export const EMAIL_TEMPLATES_RETRIEVE_REQUEST = 'EMAIL_TEMPLATES_RETRIEVE_REQUEST';
export const EMAIL_TEMPLATES_RETRIEVE_REQUEST_SUCCESS = 'EMAIL_TEMPLATES_RETRIEVE_REQUEST_SUCCESS';

export const CRASH_HANDLE_GLOBAL_ERROR = 'CRASH_HANDLE_GLOBAL_ERROR';
