export const layersJSON = (networkContext: any) => {
  return [
    {
      id: 'invasivesbc_records',
      name: 'INVASIVESBC Records',
      source: 'LEAN_ACTIVITIES',
      order: 0,
      zIndex: 6000,
      loaded: 70,
      enabled: false,
      children: [
        {
          id: 'terrestrial_observations',
          name: 'Terrestrial Observations',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'TERRESTRIAL_OBSERVATIONS',
          color_code: '#000',
          order: 0,
          opacity: 0.4,
          zIndex: 120,
          loaded: 70,
          enabled: false
        },
        {
          id: 'aquatic_observations',
          name: 'Aquatic Abservations',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'AQUATIC_OBSERVATIONS',
          color_code: '#000',
          order: 1,
          opacity: 0.4,
          zIndex: 110,
          loaded: 70,
          enabled: false
        },
        {
          id: 'terrestrial_chemical_treatment',
          name: 'Terrestrial Chemical Treatment',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'TERRESTRIAL_CHEMICAL_TREATMENT',
          color_code: '#000',
          order: 2,
          opacity: 0.4,
          zIndex: 100,
          loaded: 70,
          enabled: false
        },
        {
          id: 'aquatic_chemical_treatment',
          name: 'Aquatic Chemical Treatment',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'AQUATIC_CHEMICAL_TREATMENTS',
          color_code: '#000',
          order: 3,
          opacity: 0.4,
          zIndex: 90,
          loaded: 70,
          enabled: false
        },
        {
          id: 'terrestrial_mechanical_treatment',
          name: 'Terrestrial Mechanical Treatment',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'TERRESTRIAL_MECHANICAL_TREATMENT',
          color_code: '#000',
          order: 4,
          opacity: 0.4,
          zIndex: 80,
          loaded: 70,
          enabled: false
        },
        {
          id: 'aquatic_mechanical_treatment',
          name: 'Aquatic Mechanical Treatment',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'AQUATIC_MECHANICAL_TREATMENT',
          color_code: '#000',
          order: 5,
          opacity: 0.4,
          zIndex: 70,
          loaded: 70,
          enabled: false
        },
        {
          id: 'chemical_monitoring',
          name: 'Chemical Monitoring',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'CHEMICAL_MONITORING',
          color_code: '#000',
          order: 6,
          opacity: 0.4,
          zIndex: 60,
          loaded: 70,
          enabled: false
        },
        {
          id: 'terrestrial_monitoring',
          name: 'Terrestrial Monitoring',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'TERRESTRIAL_MONITORING',
          color_code: '#000',
          order: 7,
          opacity: 0.4,
          zIndex: 50,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_collection',
          name: 'Biocontrol Collection',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_COLLECTION',
          color_code: '#000',
          order: 8,
          opacity: 0.4,
          zIndex: 40,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_release',
          name: 'Biocontrol Release',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_RELEASE',
          color_code: '#000',
          order: 9,
          opacity: 0.4,
          zIndex: 30,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_dispersal_monitoring',
          name: 'Biocontrol Dispersal Monitoring',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_DISPERSAL_MONITORING',
          color_code: '#000',
          order: 10,
          opacity: 0.4,
          zIndex: 20,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_release_monitoring',
          name: 'Biocontrol Release Monitoring',
          source: 'LEAN_ACTIVITIES',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_RELEASE_MONITORING',
          color_code: '#000',
          order: 11,
          opacity: 0.4,
          zIndex: 10,
          loaded: 70,
          enabled: false
        }
      ]
    },
    {
      id: 'iapp_records',
      name: 'IAPP Records',
      source: 'LEAN_POI',
      order: 1,
      zIndex: 5000,
      loaded: 70,
      enabled: false,
      children: [
        {
          id: 'sites',
          name: 'Sites',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'SITES',
          color_code: '#000',
          order: 0,
          opacity: 0.4,
          zIndex: 80,
          loaded: 70,
          enabled: false
        },
        {
          id: 'surveys',
          name: 'Surveys',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'SURVEYS',
          color_code: '#000',
          order: 1,
          opacity: 0.4,
          zIndex: 70,
          loaded: 70,
          enabled: false
        },
        {
          id: 'chemical_treatment',
          name: 'Chemical Treatment',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'CHEMICAL_TREATMENT',
          color_code: '#000',
          order: 2,
          opacity: 0.4,
          zIndex: 60,
          loaded: 70,
          enabled: false
        },
        {
          id: 'mechanical_treatment',
          name: 'Mechanical Treatment',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'MECHANICAL_TREATMENTS',
          color_code: '#000',
          order: 3,
          opacity: 0.4,
          zIndex: 50,
          loaded: 70,
          enabled: false
        },
        {
          id: 'monitoring_records',
          name: 'Monitoring Records',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'MONITORING_RECORDS',
          color_code: '#000',
          order: 4,
          opacity: 0.4,
          zIndex: 40,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_release',
          name: 'Biocontrol Release',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_RELEASE',
          color_code: '#000',
          order: 5,
          opacity: 0.4,
          zIndex: 30,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_dispersal',
          name: 'Biocontrol Dispersal',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_DISPERSAL',
          color_code: '#000',
          order: 6,
          opacity: 0.4,
          zIndex: 20,
          loaded: 70,
          enabled: false
        },
        {
          id: 'biocontrol_monitoring',
          name: 'Biocontrol Monitoring',
          source: 'LEAN_POI',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'BIOCONTROL_MONITORING',
          color_code: '#000',
          order: 7,
          opacity: 0.4,
          zIndex: 10,
          loaded: 70,
          enabled: false
        }
      ]
    },
    {
      id: 'administrative_boundaries',
      name: 'Administrative Boundaries',
      source: ['DATABC', 'INVASIVESBC'],
      order: 2,
      zIndex: 4000,
      loaded: 70,
      enabled: false,
      children: [
        {
          id: 'regional_districts',
          name: 'Regional Districts - Legally Defined Administrative Areas of BC',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_LEGAL_ADMIN_BOUNDARIES.ABMS_REGIONAL_DISTRICTS_SP',
          color_code: '#000',
          order: 0,
          opacity: 0.4,
          zIndex: 50,
          loaded: 70,
          enabled: false
        },
        {
          id: 'municipality_boundaries',
          name: 'Municipality Boundaries',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_TANTALIS.TA_MUNICIPALITIES_SVW',
          color_code: '#000',
          order: 1,
          opacity: 0.4,
          zIndex: 40,
          loaded: 70,
          enabled: false
        },
        {
          id: 'first_nations_treaty_lands',
          name: 'First Nations Treaty Lands',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_LEGAL_ADMIN_BOUNDARIES.FNT_TREATY_LAND_SP',
          color_code: '#000',
          order: 2,
          opacity: 0.4,
          zIndex: 30,
          loaded: 70,
          enabled: false
        },
        {
          id: 'jurisdiction_layer',
          name: 'Jurisdiction Layer',
          source: 'INVASIVESBC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'JURISDICTION_LAYER',
          color_code: '#000',
          order: 3,
          opacity: 0.4,
          zIndex: 20,
          loaded: 70,
          enabled: false
        },
        {
          id: 'riso_boundaries',
          name: 'RISO Boundaries',
          source: 'INVASIVESBC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'RISO_BOUNDARIES',
          color_code: '#000',
          order: 4,
          opacity: 0.4,
          zIndex: 10,
          loaded: 70,
          enabled: false
        }
      ]
    },
    {
      id: 'aquatic_layers_and_wells',
      name: 'Aquatic Layers and Wells',
      source: 'DATABC',
      order: 3,
      zIndex: 3000,
      loaded: 70,
      enabled: false,
      children: [
        {
          id: 'bc_major_watersheds',
          name: 'BC Major Watersheds',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_BASEMAPPING.BC_MAJOR_WATERSHEDS',
          color_code: '#000',
          order: 0,
          opacity: 0.4,
          zIndex: 70,
          loaded: 70,
          enabled: false
        },
        {
          id: 'freshwater_atlas_rivers',
          name: 'Freshwater Atlas Rivers',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_BASEMAPPING.FWA_RIVERS_POLY',
          color_code: '#000',
          order: 1,
          opacity: 0.4,
          zIndex: 60,
          loaded: 70,
          enabled: false
        },
        {
          id: 'freshwater_lakes',
          name: 'Freshwater Lakes',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_LAND_AND_NATURAL_RESOURCE.EAUBC_LAKES_SP',
          color_code: '#000',
          order: 2,
          opacity: 0.4,
          zIndex: 50,
          loaded: 70,
          enabled: false
        },
        {
          id: 'freshwater_atlas_stream_network',
          name: 'Freshwater Atlas Stream Network',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_BASEMAPPING.FWA_STREAM_NETWORKS_SP',
          color_code: '#000',
          order: 3,
          opacity: 0.4,
          zIndex: 40,
          loaded: 70,
          enabled: false
        },
        {
          id: 'water_licenses_drinking_water',
          name: 'Water Licenses Drinking Water',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_WATER_MANAGEMENT.WLS_BC_POD_DRINKNG_SOURCES_SVW',
          color_code: '#000',
          order: 4,
          opacity: 0.4,
          zIndex: 30,
          loaded: 70,
          enabled: false
        },
        {
          id: 'water_rights_licenses',
          name: 'Water Rights Licenses',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_WATER_MANAGEMENT.WLS_WATER_RIGHTS_LICENCES_SV',
          color_code: '#000',
          order: 5,
          opacity: 0.4,
          zIndex: 20,
          loaded: 70,
          enabled: false
        },
        {
          id: 'water_wells',
          name: 'Water Wells',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_WATER_MANAGEMENT.GW_WATER_WELLS_WRBC_SVW',
          color_code: '#000',
          order: 6,
          opacity: 0.4,
          zIndex: 10,
          loaded: 70,
          enabled: false
        }
      ]
    },
    {
      id: 'terrestial_layers',
      name: 'Terrestrial Layers',
      source: 'DATABC',
      order: 4,
      zIndex: 2000,
      loaded: 70,
      enabled: false,
      children: [
        {
          id: 'digital_road_atlas',
          name: 'Digital Road Atlas (DRA) - Master Partially-Attributed Roads',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_BASEMAPPING.DRA_DGTL_ROAD_ATLAS_MPAR_SP',
          color_code: '#000',
          order: 0,
          opacity: 0.4,
          zIndex: 10,
          loaded: 70,
          enabled: false
        },
        {
          id: 'city_names',
          name: 'City Names',
          source: 'DATABC',
          layer_mode: networkContext ? 'wms_online' : 'wfs_offline',
          layer_code: 'WHSE_BASEMAPPING.BC_MAJOR_CITIES_POINTS_500M',
          color_code: '#000',
          order: 1,
          opacity: 0.4,
          zIndex: 20,
          loaded: 70,
          enabled: false
        }
      ]
    },
    {
      id: 'user_uploaded_layers',
      name: 'User Uploaded Layers',
      source: 'other',
      order: 5,
      zIndex: 1000,
      loaded: 70,
      enabled: false,
      children: []
    }
  ];
};
