kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-dc"
  annotations:
    description: SchemaSpy deployment template.
    tags: schemaspy
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}${SUFFIX}"
    annotations:
      description: Exposes and load balances the application pods
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: ${NAME}${SUFFIX}
    type: ClusterIP
    sessionAffinity: None
- kind: Route
  apiVersion: v1
  metadata:
    name: "${NAME}${SUFFIX}"
  spec:
    host: "${APPLICATION_DOMAIN}"
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    path: "/"
    to:
      kind: Service
      name: "${NAME}${SUFFIX}"
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None
    status:
      ingress: null
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
    creationTimestamp: 
    labels:
      shared: 'true'
    annotations:
      description: Keeps track of changes in the application image
  spec:
    lookupPolicy:
      local: false
    tags: []
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}${SUFFIX}"
    annotations:
      description: Defines how to deploy the container.
  spec:
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: 
        limits:
          cpu: 750m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      type: Recreate
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          name: "${NAME}:${VERSION}"
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      deploymentConfig: ${NAME}${SUFFIX}
    template:
      metadata:
        annotations: null
        creationTimestamp: null
        labels:
          deploymentConfig: ${NAME}${SUFFIX}
      spec:
        containers:
        - name: "${NAME}"
          image: " "
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: BACKEND_HOST
            value: "${BACKEND_HOST}"
          - name: DATABASE_HOST
            value: "${DB_HOST}"
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: "${NAME}${SUFFIX}"
                key: database-name
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: "${NAME}${SUFFIX}"
                key: database-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "${NAME}${SUFFIX}"
                key: database-password
          - name: DATABASE_SCHEMA
            value: "${DATABASE_SCHEMA}"
          - name: CHANGE_ID
            value: "${CHANGE_ID}"
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
- apiVersion: v1
  kind: Secret
  stringData:
    database-name: ''
    database-password: ''
    database-user: ''
  metadata:
    name: "${NAME}${SUFFIX}"
    annotations:
      as-copy-of: "${DB_HOST}"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all objects defined in this template.
  required: true
  value: schema-spy
- name: VERSION
  required: true
- name: SUFFIX
  displayName: Name Suffix
  description: A suffix appended to all objects
  required: true
  value: 'dev'
- name: DB_HOST
  displayName: Database Host name
  description: Host name for DB
  required: true
- name: BACKEND_HOST
  description: Hostname for the backend
  required: false
- name: CPU_LIMIT
  displayName: CPU Limit
  required: true
  description: Maximum amount of CPU the container can use.
  value: 400m
- name: MEMORY_LIMIT
  displayName: Memory Limit
  required: true
  description: Maximum amount of memory the container can use.
  value: 768Mi
- name: CPU_REQUEST
  displayName: CPU Limit
  required: true
  description: Maximum amount of CPU the container can use.
  value: 200m
- name: MEMORY_REQUEST
  displayName: Memory Limit
  required: true
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: APPLICATION_DOMAIN
  displayName: Application Hostname
  description: The exposed hostname that will route to the service, if left blank
    a value will be defaulted.
  value: 'seism.schemaspy.pathfinder.gov.bc.ca'
- name: DATABASE_SCHEMA
  description: Application Schema name
  value: invasivesbc
- name: CHANGE_ID
  description: Change Id or Pull request information
  value: '0'