/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ninja/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["api_protocol_activity_api_list_activities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activity Search */
        post: operations["api_protocol_activity_api_activity_search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Record
         * @description Handler for Incoming records with "Submitted" status.
         *     Performs strict validation on payload to ensure data integrity.
         *     - Adds record to the 'activity' schema
         *     - Adds Activity Modification Record if changes found (update)
         */
        post: operations["api_protocol_activity_api_submit_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Draft Record
         * @description Handler for Incoming records with "Draft" status.
         *     Performs loose validation on incoming data to remove extraneous keys and ensure payload integrity
         *     - Adds record to the 'draft_activity' schema
         */
        post: operations["api_protocol_activity_api_submit_draft_record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ninja/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity By Id */
        get: operations["api_protocol_activity_api_get_activity_by_id"];
        put?: never;
        post?: never;
        /** Delete Activity By Id */
        delete: operations["api_protocol_activity_api_delete_activity_by_id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityMinimal
         * @description Minimal fields - shared between all representations
         */
        ActivityMinimal: {
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /** Short Id */
            short_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Type */
            type: string;
            /** Subtype */
            subtype: string;
        };
        /**
         * ActivitySearchParameters
         * @description An object representing activity search parameters
         */
        ActivitySearchParameters: {
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
        };
        /** ActivitySearchResult */
        ActivitySearchResult: {
            /** Items */
            items: components["schemas"]["ActivityMinimal"][];
            search: components["schemas"]["ActivitySearchParameters"];
        };
        /** ApplicationRateHerbicide */
        ApplicationRateHerbicide: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Application Rate */
            application_rate: number;
        };
        /** BaseHerbicide */
        BaseHerbicide: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Application Rate */
            application_rate?: number | null;
        };
        /** BiocontrolCollection */
        BiocontrolCollection: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Biocontrol_Collection";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__biocontrol_collection__SubtypeData"];
        };
        /** BiocontrolCountExtended */
        BiocontrolCountExtended: {
            /** Quantity */
            quantity: number;
            /** Stage */
            stage: string;
            /**
             * Is Estimate
             * @default false
             */
            is_estimate: boolean;
            /** Plant Position */
            plant_position: string;
            /** Agent Location */
            agent_location: string;
        };
        /** BiocontrolCountSimple */
        BiocontrolCountSimple: {
            /** Quantity */
            quantity: number;
            /** Stage */
            stage: string;
            /**
             * Is Estimate
             * @default false
             */
            is_estimate: boolean;
        };
        /** BiocontrolDispersalMonitoring */
        BiocontrolDispersalMonitoring: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__SubtypeData"];
        };
        /** ChemicalContextApplicationRate */
        ChemicalContextApplicationRate: {
            /** Herbicide */
            herbicide: components["schemas"]["ApplicationRateHerbicide"][];
            /** Delivery Rate */
            delivery_rate: number;
            /** Amount Mix Used L */
            amount_mix_used_l: number;
            /** Plants Treated */
            plants_treated: components["schemas"]["TreatedPlant"][];
            /**
             * Tank Mix
             * @default false
             * @constant
             */
            tank_mix: false;
            /**
             * Calculation Type
             * @enum {string}
             */
            calculation_type: "PAR" | "D";
            /** Application Method */
            application_method: string;
            /** Results */
            results?: unknown[] | null;
        };
        /** ChemicalContextDilution */
        ChemicalContextDilution: {
            /** Herbicide */
            herbicide: components["schemas"]["BaseHerbicide"][];
            /** Amount Mix Used L */
            amount_mix_used_l: number;
            /** Dilution Percent */
            dilution_percent: number;
            /** Area Treated Sqm */
            area_treated_sqm: number;
            /** Plants Treated */
            plants_treated: components["schemas"]["TreatedPlant"][];
            /**
             * Tank Mix
             * @default false
             * @constant
             */
            tank_mix: false;
            /**
             * Calculation Type
             * @enum {string}
             */
            calculation_type: "PAR" | "D";
            /** Application Method */
            application_method: string;
            /** Results */
            results?: unknown[] | null;
        };
        /**
         * CollectionType
         * @enum {string}
         */
        CollectionType: "Timed" | "Count";
        /** Employer */
        Employer: {
            /** Employer */
            employer: string;
        };
        /**
         * Feature2D
         * @description Custom 2D GeoJSON Feature type.
         *     Pydantics build in Geometry types add 0-value Z-indexes that error out when casting to GeosGeometry.
         */
        Feature2D: {
            /**
             * Type
             * @constant
             */
            type: "Feature";
            geometry: components["schemas"]["PolygonGeometry2D"];
            /** Properties */
            properties?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * FormStatus
         * @enum {string}
         */
        FormStatus: "Draft" | "Submitted" | "Flagged" | "Deleted";
        /**
         * FundingAgency
         * @description Single Funding Agency Entry, Casts alias to match the incoming payload to the db column
         */
        FundingAgency: {
            /** Agency */
            agency: string;
        };
        /** InvasivePlantOnSite */
        InvasivePlantOnSite: {
            /** Invasive Plants On Site */
            invasive_plants_on_site: string;
        };
        /** JurisdictionSchema */
        JurisdictionSchema: {
            /** Jurisdiction */
            jurisdiction: string;
            /** Percent Covered */
            percent_covered: number;
        };
        /** LinkedActivity */
        LinkedActivity: {
            /** Label */
            label: string;
            /** Full */
            full: string;
        };
        /**
         * Media
         * @description Single Media Entry (Photo Upload) for Plant Activity Forms
         */
        Media: {
            /** Description */
            description: string;
            /** Encoded File */
            encoded_file: string;
            /** File Name */
            file_name: string;
        };
        /** MicrositeCondition */
        MicrositeCondition: {
            /** Mesoslope Position */
            mesoslope_position: string;
            /** Site Surface Shape */
            site_surface_shape: string;
        };
        /** MonitoringBiocontrolRelease */
        MonitoringBiocontrolRelease: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Monitoring_Biocontrol_Release_Plant_Terrestrial";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__SubtypeData"];
        };
        /** MonitoringChemical */
        MonitoringChemical: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Monitoring_Chemical_Plant_Terrestrial_Aquatic";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__monitoring_mechanical__SubtypeData"];
        };
        /** MonitoringMechanical */
        MonitoringMechanical: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Monitoring_Mechanical_Plant_Terrestrial_Aquatic";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__monitoring_mechanical__SubtypeData"];
        };
        /** ObservationAquaticSchema */
        ObservationAquaticSchema: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Observation_Plant_Aquatic";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__observation_aquatic__SubtypeData"];
        };
        /** ObservationTerrestrialSchema */
        ObservationTerrestrialSchema: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Observation_Plant_Terrestrial";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__observation_terrestrial__SubtypeData"];
        };
        /**
         * ObservationType
         * @enum {string}
         */
        ObservationType: "Positive" | "Negative";
        /** Participant */
        Participant: {
            /** Name */
            name: string;
            /** Pac Number */
            pac_number?: number | null;
        };
        /**
         * PlantDisposalFormat
         * @enum {string}
         */
        PlantDisposalFormat: "plants" | "m^3" | "kg";
        /** PlantHeight */
        PlantHeight: {
            /** Height Cm */
            height_cm: number;
        };
        /**
         * PolygonGeometry2D
         * @description Custom Polygon GeoJSON Type.
         *     Pydantics build in Geometry types add 0-value Z-indexes that error out when casting to GeosGeometry.
         */
        PolygonGeometry2D: {
            /**
             * Type
             * @constant
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: components["schemas"]["Position2D"][][];
        };
        /**
         * Position2D
         * @description Loosely defined coordinate type for incoming Geometry
         */
        Position2D: [
            number,
            number
        ];
        /** ProjectCode */
        ProjectCode: {
            /** Description */
            description: string;
        };
        /**
         * RecordAction
         * @enum {string}
         */
        RecordAction: "EDIT" | "DELETE" | "SUBMIT";
        /**
         * RecordMetadata
         * @description Properties related to a record, but not directly affected by the record.
         */
        RecordMetadata: {
            /** Linking Activities */
            linking_activities: {
                [key: string]: unknown;
            }[] | null;
            /** History */
            history: {
                [key: string]: unknown;
            }[] | null;
        };
        /** ShorelineType */
        ShorelineType: {
            /** Shoreline Type */
            shoreline_type: string;
            /** Percent Covered */
            percent_covered: number;
        };
        /** SingleActivityResponse */
        SingleActivityResponse: {
            /** Data */
            data: components["schemas"]["ObservationTerrestrialSchema"] | components["schemas"]["ObservationAquaticSchema"] | components["schemas"]["TreatmentBiocontrolRelease"] | components["schemas"]["BiocontrolCollection"] | components["schemas"]["TreatmentChemicalTerrestrial"] | components["schemas"]["TreatmentChemicalAquatic"] | components["schemas"]["TreatmentMechanicalTerrestrial"] | components["schemas"]["TreatmentMechanicalAquatic"] | components["schemas"]["MonitoringMechanical"] | components["schemas"]["MonitoringChemical"] | components["schemas"]["MonitoringBiocontrolRelease"] | components["schemas"]["BiocontrolDispersalMonitoring"];
            /** Available Actions */
            available_actions: components["schemas"]["RecordAction"][];
            metadata: components["schemas"]["RecordMetadata"];
        };
        /** SpecificUseType */
        SpecificUseType: {
            /** Specific Use */
            specific_use: string;
        };
        /** SpreadResultsMixin */
        SpreadResultsMixin: {
            /** Agent Density */
            agent_density?: number | null;
            /** Plant Attack */
            plant_attack?: number | null;
            /** Max Spread Distance M */
            max_spread_distance_m?: number | null;
            /** Max Spread Aspect Deg */
            max_spread_aspect_deg?: number | null;
        };
        /** TankMixChemicalContext */
        TankMixChemicalContext: {
            /** Herbicide */
            herbicide: components["schemas"]["ApplicationRateHerbicide"][];
            /** Delivery Rate */
            delivery_rate: number;
            /** Amount Mix Used L */
            amount_mix_used_l: number;
            /** Plants Treated */
            plants_treated: components["schemas"]["TreatedPlant"][];
            /**
             * Tank Mix
             * @default true
             * @constant
             */
            tank_mix: true;
            /**
             * Calculation Type
             * @enum {string}
             */
            calculation_type: "PAR" | "D";
            /** Application Method */
            application_method: string;
            /** Results */
            results?: unknown[] | null;
        };
        /** TargetPlantPhenology */
        TargetPlantPhenology: {
            /** Winter Dormant */
            winter_dormant: number;
            /** Seedlings */
            seedlings: number;
            /** Rosettes */
            rosettes: number;
            /** Bolts */
            bolts: number;
            /** Flowering */
            flowering: number;
            /** Seeds Forming */
            seeds_forming: number;
            /** Senescent */
            senescent: number;
            /** Target Plant Heights */
            target_plant_heights?: components["schemas"]["PlantHeight"][];
        };
        /** TreatedPlant */
        TreatedPlant: {
            /** Invasive Plant */
            invasive_plant: string;
            /** Percent Covered */
            percent_covered: number;
        };
        /** TreatmentBiocontrolRelease */
        TreatmentBiocontrolRelease: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Biocontrol_Release";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_biocontrol_release__SubtypeData"];
        };
        /** TreatmentChemicalAquatic */
        TreatmentChemicalAquatic: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Treatment_Chemical_Plant_Aquatic";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__BaseChemicalDetails"];
        };
        /** TreatmentChemicalTerrestrial */
        TreatmentChemicalTerrestrial: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Treatment_Chemical_Plant_Terrestrial";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__BaseChemicalDetails"];
        };
        /** TreatmentMechanicalAquatic */
        TreatmentMechanicalAquatic: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Treatment_Mechanical_Plant_Aquatic";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__SubtypeData"];
        };
        /** TreatmentMechanicalTerrestrial */
        TreatmentMechanicalTerrestrial: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Id */
            id: string;
            /** Created By */
            created_by: string;
            form_status: components["schemas"]["FormStatus"];
            /** Linked Activities */
            linked_activities: components["schemas"]["LinkedActivity"][];
            /** Employer */
            employer: components["schemas"]["Employer"][];
            /** Funding Agencies */
            funding_agencies: components["schemas"]["FundingAgency"][];
            /** Jurisdictions */
            jurisdictions: components["schemas"]["JurisdictionSchema"][];
            /** Media */
            media: components["schemas"]["Media"][];
            /** Participants */
            participants: components["schemas"]["Participant"][];
            /** Projects */
            projects: components["schemas"]["ProjectCode"][];
            /** Area M */
            area_m: number;
            shape: components["schemas"]["Feature2D"];
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /** Utm Zone */
            utm_zone: number;
            /** Access Description */
            access_description: string | null;
            /** Comment */
            comment: string | null;
            /** Location Description */
            location_description: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            subtype: "Treatment_Mechanical_Plant_Terrestrial";
            subtype_data: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__SubtypeData"];
        };
        /**
         * TreatmentPass
         * @enum {string}
         */
        TreatmentPass: "First" | "Second" | "Third" | "Greater" | "Unknown";
        /** VoucherSpecimenSchema */
        VoucherSpecimenSchema: {
            /** Voucher Sample Id */
            voucher_sample_id: string;
            /** Herbarium */
            herbarium?: string | null;
            /** Accession Number */
            accession_number?: string | null;
            /** Completed By Person */
            completed_by_person?: string | null;
            /** Completed By Org */
            completed_by_org?: string | null;
            /** Utm Zone */
            utm_zone: number;
            /** Utm Easting */
            utm_easting: number;
            /** Utm Northing */
            utm_northing: number;
            /**
             * Date Collected
             * Format: date
             */
            date_collected: string;
            /** Date Verified */
            date_verified?: string | null;
        };
        /** WaterbodyContext */
        WaterbodyContext: {
            /** Inflow Permanent */
            inflow_permanent: string[];
            /** Inflow Seasonal */
            inflow_seasonal: string[];
            /** Outflow Permanent */
            outflow_permanent: string[];
            /** Outflow Seasonal */
            outflow_seasonal: string[];
            /** Access */
            access: string | null;
            /** Comment */
            comment: string | null;
            /** Name Local */
            name_local: string | null;
            /** Name Gazetted */
            name_gazetted: string | null;
            tidal_influence: components["schemas"]["YesNoUnknown"];
            /** Type */
            type: string;
            /** Colour */
            colour: string | null;
            /** Max Depth M */
            max_depth_m: number | null;
            /** Secchi Depth */
            secchi_depth: number | null;
        };
        /** WeatherConditions */
        WeatherConditions: {
            /** Comments */
            comments?: string | null;
            /** Cloud Cover */
            cloud_cover: string;
            /** Precipitation */
            precipitation: string;
            /** Wind Direction */
            wind_direction: string;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Temperature */
            temperature: number;
        };
        /** WellEntry */
        WellEntry: {
            /** Well Tag */
            well_tag: string;
            /** Distance */
            distance: number;
        };
        /**
         * YesNo
         * @enum {string}
         */
        YesNo: "Yes" | "No";
        /**
         * YesNoUnknown
         * @enum {string}
         */
        YesNoUnknown: "Yes" | "No" | "Unknown";
        /** Entry */
        api__protocol__activity__plant_subtypes__biocontrol_collection__Entry: {
            /** Invasive Plant */
            invasive_plant: string;
            /** Biological Agent */
            biological_agent: string;
            /** Historical Iapp Site */
            historical_iapp_site?: number | null;
            collection_type: components["schemas"]["CollectionType"];
            /** Plant Count Collection */
            plant_count_collection?: number | null;
            /** Time Collection Duration Minutes */
            time_collection_duration_minutes?: number | null;
            /** Collection Method */
            collection_method: string;
            /** Number Of Sweeps */
            number_of_sweeps?: number | null;
            /**
             * Start Time Collecting
             * Format: date-time
             */
            start_time_collecting: string;
            /**
             * End Time Collecting
             * Format: date-time
             */
            end_time_collecting: string;
            /** Comment */
            comment: string | null;
            /** Actual Biological Agents */
            actual_biological_agents: components["schemas"]["BiocontrolCountSimple"][];
            /** Estimated Biological Agents */
            estimated_biological_agents: components["schemas"]["BiocontrolCountSimple"][];
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__biocontrol_collection__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__biocontrol_collection__Entry"][];
            microsite_conditions: components["schemas"]["MicrositeCondition"];
            weather_conditions: components["schemas"]["WeatherConditions"];
            target_plant_phenology?: components["schemas"]["TargetPlantPhenology"] | null;
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__Entry: {
            /** Biocontrol Agent */
            biocontrol_agent: string;
            /** Biocontrol Present */
            biocontrol_present: boolean;
            /** Invasive Plant */
            invasive_plant: string;
            monitoring_type: components["schemas"]["CollectionType"];
            /** Plant Count */
            plant_count?: number | null;
            linear_segment?: components["schemas"]["YesNoUnknown"] | null;
            /** Monitoring Method */
            monitoring_method: string;
            /** Count Duration Minutes */
            count_duration_minutes?: number | null;
            /** Location Agent Found */
            location_agent_found: string[];
            /** Number Of Sweeps */
            number_of_sweeps?: number | null;
            /** Sign Of Biocontrol Presence */
            sign_of_biocontrol_presence: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Stop Time
             * Format: date-time
             */
            stop_time: string;
            suitable_for_collection?: components["schemas"]["YesNoUnknown"] | null;
            /**
             * Actual Biological Agents
             * @default []
             */
            actual_biological_agents: components["schemas"]["BiocontrolCountExtended"][];
            /**
             * Estimated Biological Agents
             * @default []
             */
            estimated_biological_agents: components["schemas"]["BiocontrolCountExtended"][];
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__Entry"][];
            microsite_conditions: components["schemas"]["MicrositeCondition"];
            weather_conditions: components["schemas"]["WeatherConditions"];
            target_plant_phenology?: components["schemas"]["TargetPlantPhenology"] | null;
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__Entry: {
            /** Biocontrol Agent */
            biocontrol_agent: string;
            /** Biocontrol Present */
            biocontrol_present: boolean;
            /** Invasive Plant */
            invasive_plant: string;
            monitoring_type: components["schemas"]["CollectionType"];
            /** Monitoring Method */
            monitoring_method: string;
            /** Count Duration Minutes */
            count_duration_minutes?: number | null;
            /** Plant Count */
            plant_count?: number | null;
            /** Location Agent Found */
            location_agent_found: string[];
            /** Sign Of Biocontrol Presence */
            sign_of_biocontrol_presence: string[];
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * Stop Time
             * Format: date-time
             */
            stop_time: string;
            suitable_for_collection?: components["schemas"]["YesNoUnknown"] | null;
            /** Number Of Sweeps */
            number_of_sweeps?: number | null;
            /** Actual Biological Agents */
            actual_biological_agents: components["schemas"]["BiocontrolCountExtended"][];
            /** Estimated Biological Agents */
            estimated_biological_agents: components["schemas"]["BiocontrolCountExtended"][];
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__Entry"][];
            microsite_conditions: components["schemas"]["MicrositeCondition"];
            weather_conditions: components["schemas"]["WeatherConditions"];
            spread_results?: components["schemas"]["SpreadResultsMixin"] | null;
            target_plant_phenology?: components["schemas"]["TargetPlantPhenology"] | null;
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__monitoring_mechanical__Entry: {
            /** Invasive Plant */
            invasive_plant?: string | null;
            /** Invasive Plant Aquatic */
            invasive_plant_aquatic?: string | null;
            evidence_of_treatment: components["schemas"]["YesNo"];
            treatment_pass?: components["schemas"]["TreatmentPass"] | null;
            /** Comment */
            comment?: string | null;
            /** Invasive Plants On Site */
            invasive_plants_on_site: components["schemas"]["InvasivePlantOnSite"][];
            /** Management Efficacy Rating */
            management_efficacy_rating: string;
            /** Treatment Efficacy Rating */
            treatment_efficacy_rating?: string | null;
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__monitoring_mechanical__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__monitoring_mechanical__Entry"][];
        };
        /** Context */
        api__protocol__activity__plant_subtypes__observation_aquatic__Context: {
            suitable_for_biocontrol: components["schemas"]["YesNoUnknown"];
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__observation_aquatic__Entry: {
            /** Sample Point Id */
            sample_point_id?: string | null;
            observation_type: components["schemas"]["ObservationType"];
            /** Invasive Plant */
            invasive_plant: string;
            /** Density */
            density?: string | null;
            /** Distribution */
            distribution?: string | null;
            /** Life Stage */
            life_stage?: string | null;
            voucher_specimen?: components["schemas"]["VoucherSpecimenSchema"] | null;
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__observation_aquatic__SubtypeData: {
            context: components["schemas"]["api__protocol__activity__plant_subtypes__observation_aquatic__Context"];
            waterbody_context: components["schemas"]["WaterbodyContext"];
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__observation_aquatic__Entry"][];
            /** Substrate Type */
            substrate_type: string[];
            /** Water Use */
            water_use: string[];
            /** Waterlevel Management */
            waterlevel_management: string[];
            /** Adjacent Land Use */
            adjacent_land_use: string[];
            pretreatment_observation: components["schemas"]["YesNoUnknown"];
            /** Shoreline Types */
            shoreline_types: components["schemas"]["ShorelineType"][];
        };
        /** Context */
        api__protocol__activity__plant_subtypes__observation_terrestrial__Context: {
            research_observation: components["schemas"]["YesNoUnknown"];
            suitable_for_biocontrol_agent: components["schemas"]["YesNoUnknown"];
            visible_well_nearby: components["schemas"]["YesNoUnknown"];
            /** Aspect */
            aspect: string;
            /** Slope Percent */
            slope_percent: string;
            /** Soil Texture */
            soil_texture: string | null;
            /** Specific Uses */
            specific_uses: components["schemas"]["SpecificUseType"][];
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__observation_terrestrial__Entry: {
            observation_type: components["schemas"]["ObservationType"];
            /** Invasive Plant */
            invasive_plant: string;
            /** Density */
            density?: string | null;
            /** Distribution */
            distribution?: string | null;
            /** Life Stage */
            life_stage?: string | null;
            voucher_specimen?: components["schemas"]["VoucherSpecimenSchema"] | null;
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__observation_terrestrial__SubtypeData: {
            context: components["schemas"]["api__protocol__activity__plant_subtypes__observation_terrestrial__Context"];
            pretreatment_observation: components["schemas"]["YesNoUnknown"];
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__observation_terrestrial__Entry"][];
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__treatment_biocontrol_release__Entry: {
            /** Invasive Plant */
            invasive_plant: string;
            /** Biocontrol Agent */
            biocontrol_agent: string;
            linear_segment: components["schemas"]["YesNoUnknown"];
            /** Mortality */
            mortality: number;
            /** Agent Source */
            agent_source: string;
            /**
             * Collection Date
             * Format: date-time
             */
            collection_date: string;
            /** Plant Collected From */
            plant_collected_from?: string;
            /** Plant Collected From Manual */
            plant_collected_from_manual?: string | null;
            /** Actual Biological Agents */
            actual_biological_agents: components["schemas"]["BiocontrolCountSimple"][];
            /** Estimated Biological Agents */
            estimated_biological_agents: components["schemas"]["BiocontrolCountSimple"][];
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__treatment_biocontrol_release__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_biocontrol_release__Entry"][];
            microsite_conditions: components["schemas"]["MicrositeCondition"];
            weather_conditions: components["schemas"]["WeatherConditions"];
            target_plant_phenology?: components["schemas"]["TargetPlantPhenology"] | null;
        };
        /** BaseChemicalDetails */
        api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__BaseChemicalDetails: {
            context: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__Context"];
            /** Well Entries */
            well_entries: components["schemas"]["WellEntry"][];
            /** Treatment Context */
            treatment_context: components["schemas"]["TankMixChemicalContext"] | components["schemas"]["ChemicalContextDilution"] | components["schemas"]["ChemicalContextApplicationRate"];
        };
        /** Context */
        api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__Context: {
            /** Humidity */
            humidity?: number | null;
            /** Temperature C */
            temperature_c: number;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Wind Direction */
            wind_direction: string;
            /** Pesticide Employer Code */
            pesticide_employer_code?: string | null;
            /** Pesticide Use Permit */
            pesticide_use_permit?: string | null;
            /** Pest Management Plan */
            pest_management_plan?: string | null;
            /** Pest Management Plan Manual */
            pest_management_plan_manual?: string | null;
            treatment_notice_signs: components["schemas"]["YesNoUnknown"];
            /** Precautionary Statement */
            precautionary_statement: string;
            /**
             * Application Start Time
             * Format: date-time
             */
            application_start_time: string;
            /** Ntz Reduction */
            ntz_reduction: boolean;
            /** Rationale For Ntz Reduction */
            rationale_for_ntz_reduction?: string | null;
            /** Additional Unmapped Well Water */
            additional_unmapped_well_water: boolean;
            /** Pest Injury Threshold Determination */
            pest_injury_threshold_determination: boolean;
        };
        /** BaseChemicalDetails */
        api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__BaseChemicalDetails: {
            context: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__Context"];
            /** Well Entries */
            well_entries: components["schemas"]["WellEntry"][];
            /** Treatment Context */
            treatment_context: components["schemas"]["TankMixChemicalContext"] | components["schemas"]["ChemicalContextDilution"] | components["schemas"]["ChemicalContextApplicationRate"];
        };
        /** Context */
        api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__Context: {
            /** Humidity */
            humidity?: number | null;
            /** Temperature C */
            temperature_c: number;
            /** Wind Speed Kmh */
            wind_speed_kmh: number;
            /** Wind Direction */
            wind_direction: string;
            /** Pesticide Employer Code */
            pesticide_employer_code?: string | null;
            /** Pesticide Use Permit */
            pesticide_use_permit?: string | null;
            /** Pest Management Plan */
            pest_management_plan?: string | null;
            /** Pest Management Plan Manual */
            pest_management_plan_manual?: string | null;
            treatment_notice_signs: components["schemas"]["YesNoUnknown"];
            /** Precautionary Statement */
            precautionary_statement: string;
            /**
             * Application Start Time
             * Format: date-time
             */
            application_start_time: string;
            /** Ntz Reduction */
            ntz_reduction: boolean;
            /** Rationale For Ntz Reduction */
            rationale_for_ntz_reduction?: string | null;
            /** Additional Unmapped Well Water */
            additional_unmapped_well_water: boolean;
            /** Pest Injury Threshold Determination */
            pest_injury_threshold_determination: boolean;
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__Entry: {
            /** Disposed Material Amount */
            disposed_material_amount: number | null;
            disposed_material_format: components["schemas"]["PlantDisposalFormat"] | null;
            /** Disposal Method */
            disposal_method: string;
            /** Invasive Plant */
            invasive_plant: string;
            /** Mechanical Method */
            mechanical_method: string;
            /** Treated Area Msq */
            treated_area_msq: number;
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__Entry"][];
            /** Shoreline Types */
            shoreline_types: components["schemas"]["ShorelineType"][];
            /** Authorization Information */
            authorization_information?: string | null;
        };
        /** Entry */
        api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__Entry: {
            /** Disposed Material Amount */
            disposed_material_amount: number | null;
            disposed_material_format: components["schemas"]["PlantDisposalFormat"] | null;
            /** Disposal Method */
            disposal_method: string;
            /** Invasive Plant */
            invasive_plant: string;
            /** Mechanical Method */
            mechanical_method: string;
            /** Treated Area Msq */
            treated_area_msq: number;
        };
        /** SubtypeData */
        api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__SubtypeData: {
            /** Entries */
            entries: components["schemas"]["api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__Entry"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type ActivityMinimal = components['schemas']['ActivityMinimal'];
export type ActivitySearchParameters = components['schemas']['ActivitySearchParameters'];
export type ActivitySearchResult = components['schemas']['ActivitySearchResult'];
export type ApplicationRateHerbicide = components['schemas']['ApplicationRateHerbicide'];
export type BaseHerbicide = components['schemas']['BaseHerbicide'];
export type BiocontrolCollection = components['schemas']['BiocontrolCollection'];
export type BiocontrolCountExtended = components['schemas']['BiocontrolCountExtended'];
export type BiocontrolCountSimple = components['schemas']['BiocontrolCountSimple'];
export type BiocontrolDispersalMonitoring = components['schemas']['BiocontrolDispersalMonitoring'];
export type ChemicalContextApplicationRate = components['schemas']['ChemicalContextApplicationRate'];
export type ChemicalContextDilution = components['schemas']['ChemicalContextDilution'];
export type CollectionType = components['schemas']['CollectionType'];
export type Employer = components['schemas']['Employer'];
export type Feature2D = components['schemas']['Feature2D'];
export type FormStatus = components['schemas']['FormStatus'];
export type FundingAgency = components['schemas']['FundingAgency'];
export type InvasivePlantOnSite = components['schemas']['InvasivePlantOnSite'];
export type JurisdictionSchema = components['schemas']['JurisdictionSchema'];
export type LinkedActivity = components['schemas']['LinkedActivity'];
export type Media = components['schemas']['Media'];
export type MicrositeCondition = components['schemas']['MicrositeCondition'];
export type MonitoringBiocontrolRelease = components['schemas']['MonitoringBiocontrolRelease'];
export type MonitoringChemical = components['schemas']['MonitoringChemical'];
export type MonitoringMechanical = components['schemas']['MonitoringMechanical'];
export type ObservationAquaticSchema = components['schemas']['ObservationAquaticSchema'];
export type ObservationTerrestrialSchema = components['schemas']['ObservationTerrestrialSchema'];
export type ObservationType = components['schemas']['ObservationType'];
export type Participant = components['schemas']['Participant'];
export type PlantDisposalFormat = components['schemas']['PlantDisposalFormat'];
export type PlantHeight = components['schemas']['PlantHeight'];
export type PolygonGeometry2D = components['schemas']['PolygonGeometry2D'];
export type Position2D = components['schemas']['Position2D'];
export type ProjectCode = components['schemas']['ProjectCode'];
export type RecordAction = components['schemas']['RecordAction'];
export type RecordMetadata = components['schemas']['RecordMetadata'];
export type ShorelineType = components['schemas']['ShorelineType'];
export type SingleActivityResponse = components['schemas']['SingleActivityResponse'];
export type SpecificUseType = components['schemas']['SpecificUseType'];
export type SpreadResultsMixin = components['schemas']['SpreadResultsMixin'];
export type TankMixChemicalContext = components['schemas']['TankMixChemicalContext'];
export type TargetPlantPhenology = components['schemas']['TargetPlantPhenology'];
export type TreatedPlant = components['schemas']['TreatedPlant'];
export type TreatmentBiocontrolRelease = components['schemas']['TreatmentBiocontrolRelease'];
export type TreatmentChemicalAquatic = components['schemas']['TreatmentChemicalAquatic'];
export type TreatmentChemicalTerrestrial = components['schemas']['TreatmentChemicalTerrestrial'];
export type TreatmentMechanicalAquatic = components['schemas']['TreatmentMechanicalAquatic'];
export type TreatmentMechanicalTerrestrial = components['schemas']['TreatmentMechanicalTerrestrial'];
export type TreatmentPass = components['schemas']['TreatmentPass'];
export type VoucherSpecimenSchema = components['schemas']['VoucherSpecimenSchema'];
export type WaterbodyContext = components['schemas']['WaterbodyContext'];
export type WeatherConditions = components['schemas']['WeatherConditions'];
export type WellEntry = components['schemas']['WellEntry'];
export type YesNo = components['schemas']['YesNo'];
export type YesNoUnknown = components['schemas']['YesNoUnknown'];
export type ApiProtocolActivityPlantSubtypesBiocontrolCollectionEntry = components['schemas']['api__protocol__activity__plant_subtypes__biocontrol_collection__Entry'];
export type ApiProtocolActivityPlantSubtypesBiocontrolCollectionSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__biocontrol_collection__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesBiocontrolDispersalMonitoringEntry = components['schemas']['api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__Entry'];
export type ApiProtocolActivityPlantSubtypesBiocontrolDispersalMonitoringSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__biocontrol_dispersal_monitoring__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesMonitoringBiocontrolReleaseEntry = components['schemas']['api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__Entry'];
export type ApiProtocolActivityPlantSubtypesMonitoringBiocontrolReleaseSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__monitoring_biocontrol_release__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesMonitoringMechanicalEntry = components['schemas']['api__protocol__activity__plant_subtypes__monitoring_mechanical__Entry'];
export type ApiProtocolActivityPlantSubtypesMonitoringMechanicalSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__monitoring_mechanical__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesObservationAquaticContext = components['schemas']['api__protocol__activity__plant_subtypes__observation_aquatic__Context'];
export type ApiProtocolActivityPlantSubtypesObservationAquaticEntry = components['schemas']['api__protocol__activity__plant_subtypes__observation_aquatic__Entry'];
export type ApiProtocolActivityPlantSubtypesObservationAquaticSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__observation_aquatic__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesObservationTerrestrialContext = components['schemas']['api__protocol__activity__plant_subtypes__observation_terrestrial__Context'];
export type ApiProtocolActivityPlantSubtypesObservationTerrestrialEntry = components['schemas']['api__protocol__activity__plant_subtypes__observation_terrestrial__Entry'];
export type ApiProtocolActivityPlantSubtypesObservationTerrestrialSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__observation_terrestrial__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesTreatmentBiocontrolReleaseEntry = components['schemas']['api__protocol__activity__plant_subtypes__treatment_biocontrol_release__Entry'];
export type ApiProtocolActivityPlantSubtypesTreatmentBiocontrolReleaseSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__treatment_biocontrol_release__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesTreatmentChemicalAquaticBaseChemicalDetails = components['schemas']['api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__BaseChemicalDetails'];
export type ApiProtocolActivityPlantSubtypesTreatmentChemicalAquaticContext = components['schemas']['api__protocol__activity__plant_subtypes__treatment_chemical_aquatic__Context'];
export type ApiProtocolActivityPlantSubtypesTreatmentChemicalTerrestrialBaseChemicalDetails = components['schemas']['api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__BaseChemicalDetails'];
export type ApiProtocolActivityPlantSubtypesTreatmentChemicalTerrestrialContext = components['schemas']['api__protocol__activity__plant_subtypes__treatment_chemical_terrestrial__Context'];
export type ApiProtocolActivityPlantSubtypesTreatmentMechanicalAquaticEntry = components['schemas']['api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__Entry'];
export type ApiProtocolActivityPlantSubtypesTreatmentMechanicalAquaticSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__treatment_mechanical_aquatic__SubtypeData'];
export type ApiProtocolActivityPlantSubtypesTreatmentMechanicalTerrestrialEntry = components['schemas']['api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__Entry'];
export type ApiProtocolActivityPlantSubtypesTreatmentMechanicalTerrestrialSubtypeData = components['schemas']['api__protocol__activity__plant_subtypes__treatment_mechanical_terrestrial__SubtypeData'];
export type $defs = Record<string, never>;
export interface operations {
    api_protocol_activity_api_list_activities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityMinimal"][];
                };
            };
        };
    };
    api_protocol_activity_api_activity_search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivitySearchParameters"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivitySearchResult"];
                };
            };
        };
    };
    api_protocol_activity_api_submit_record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_protocol_activity_api_submit_draft_record: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_protocol_activity_api_get_activity_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SingleActivityResponse"];
                };
            };
        };
    };
    api_protocol_activity_api_delete_activity_by_id: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
