/**
 * @desc Interfaces for Prompt System, contains all props for inputs.
 * @external {@link https://github.com/bcgov/invasivesbc/wiki/User-Prompt-System }
 */
import { PromptTypes } from 'constants/promptEnums';

export interface ReduxPayload {
  type: string;
  payload?: Record<string, any>;
}
/**
 * @interface BasePromptInterface Confirmation Modal Prompts
 * @property {string} cancelText Text override for 'Cancel' button text
 * @property {string} confirmText Text override for 'Confirm' button text
 * @property {string} id Id for a given Prompt (Used for deleting)
 * @property {string[] | string} prompt Main text body, Can use array to handle multiple paragraphs
 * @property {string} title Title for modal
 * @property {PromptTypes} type Type of Modal being rendered (used by controller), Generated by helper function
 */
interface BasePromptInterface {
  cancelText?: string;
  confirmText?: string;
  id?: string;
  prompt: string[] | string;
  title: string;
  type?: PromptTypes;
}
/**
 * @interface ConfirmationModalInterface
 * @extends BasePromptInterface
 * @property { (boolean) => void | ReduxPayload[] } callback Action result for user input. if an array is returned, fires all redux actions contained
 */
export interface ConfirmationModalInterface extends BasePromptInterface {
  callback: (input: boolean) => void | ReduxPayload[];
}

/**
 * @interface DateModalInterface
 * @extends BasePromptInterface
 * @property { (Date) => void | ReduxPayload[] } callback Action result for user input. if an array is returned, fires all redux actions contained
 * @property {string} label Override label for user input field
 * @property {Date} max Latest valid date
 * @property {Date} min Earliest valid date
 */
export interface DateModalInterface extends BasePromptInterface {
  callback: (input: Date) => void | ReduxPayload[];
  label?: string;
  max?: Date;
  min?: Date;
}

/**
 * @interface NumberModalInterface
 * @extends BasePromptInterface
 * @property {boolean} acceptFloats Allow user to enter floats as input value
 * @property { (number) => void | ReduxPayload[] } callback Action result for user input. if an array is returned, fires all redux actions contained
 * @property {string} label Override label for user input field
 * @property {number} max maximum range for response
 * @property {number} min minimum range for response
 * @property {number[]} selectOptions curated set of options user can select from
 */
export interface NumberModalInterface extends BasePromptInterface {
  acceptFloats?: boolean;
  callback: (input: number) => void | ReduxPayload[];
  label?: string;
  max?: number;
  min?: number;
  selectOptions?: number[];
}

/**
 * @type {Props} Confirmation Modal Prompts
 * @extends BasePromptInterface
 * @property {string} label Override label for user input field
 * @property {number} min minimum character length for response
 * @property {number} max maximum character length for response
 * @property {RegExp} regex Regex pattern to validate user input against
 * @property {string} regexErrorText Override error message for regex errors, otherwise shows pattern
 * @property {string[]} selectOptions curated set of options user can select from
 */
export interface TextModalInterface extends BasePromptInterface {
  callback: (input: string) => void | ReduxPayload[];
  label?: string;
  max?: number;
  min?: number;
  regex?: RegExp;
  regexErrorText?: string;
  selectOptions?: string[];
}
