FROM node:16.14-alpine

# Create app directory
ENV HOME_ROOT=/opt/app-root
ENV HOME=/opt/app-root/src

RUN mkdir -p $HOME

WORKDIR $HOME_ROOT

WORKDIR $HOME

COPY ./package*.json ./

RUN npm set progress=false &&  npm ci

VOLUME ${HOME}/node_modules
ENTRYPOINT /usr/bin/tail -f /dev/null
