openapi: 3.0.0

info:
  version: 0.0.0
  title: invasivesbc-api-mobile
  description: API for InvasivesBC mobile.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:3002/api
    description: local api
  - url: http://localhost:7080/api
    description: local api via docker
  - url: https://api-mobile-dev-invasivesbc.pathfinder.gov.bc.ca
    description: deployed api in dev environment
  - url: https://api-mobile-test-invasivesbc.pathfinder.gov.bc.ca
    description: deployed api in test environment
  - url: https://api-mobile-invasivesbc.pathfinder.gov.bc.ca
    description: deployed api in prod environmen

tags:
  - name: misc
    description: Miscellaneous endpoints
  - name: activity
    description: |
      Activity endpoints
      An activity is a parent classification that contains Observations, Treatments, and Monitoring 'activities'
  - name: observation
    description: Observation activity endpoints
  - name: plant
    description: Plant endpoints
  - name: code
    description: Code endpoints
  - name: media
    description: Media endpoints

externalDocs:
  description: Visit GitHub to find out more about this API
  url: https://github.com/bcgov/lucy-web.git

## paths are generated via express-openapi based on the ./src/paths/* structure
paths: {}

# See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#componentsObject for supported component types
components:
  securitySchemes:
    Bearer: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
      description: |
        To access the authenticated api routes, a valid JWT token must be present in the 'Authorization' header.
        The 'Authorization' header value must be of the form: `Bearer xxxxxx.yyyyyyy.zzzzzz`

  responses:
    "401":
      description: Unauthorized user
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    "400":
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    "503":
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    default:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Error:
      description: Error response object.
      properties:
        status:
          type: number
        message:
          type: string
        errors:
          type: array
          items:
            type: string

    Activity:
      description:
        Activity main object.
      type: object
      required:
        - species_agency_code
        - activity_status
      properties:
        species_agency_code:
          type: string
          title: "Agency"
        jurisdiction_code:
          type: string
          title: "Jurisdiction"
        activity_status:
          type: string
          title: "Activity status"
        species_id:
          type: string
          title: "Species"
        general_comment:
          type: string
          title: "Comment"
          maximum: 300
        access_description:
          type: string
          title: "Access Description"
        primary_paper_file_id:
          type: string
          title: "Primary File"
        secondary_paper_file_id:
          type: string
          title: "Secondary File"
        media_indicator:
          type: boolean
          title: "Photo"
        media:
          type: array
          title: "Photos"
          items:
            $ref: "#/components/schemas/Media"

    Observation:
      description: |
        Observation main object.
      type: object
      required:
        - observation_id
        - observation_date
        - observation time
        - observation_type
      properties:
        observation_id:
          type: number
          title: "ID"
        observation_date:
          type: string
          title: "Date"
        observation_time:
          type: string
          title: "Time"
        observation_type:
          type: string
          title: "Type"
        observer_first_name:
          type: string
          title: "First Name"
        observer_last_name:
          type: string
          title: "Last Name"
        reported_area:
          type: integer
          title: "Area"
        sample_taken:
          type: boolean
          title: "Sample Taken"
        sample_number:
          type: string
          title: "Sample Number"
        negative_obs_ind:
          type: boolean
          title: "Negative Observation"
        subType:
          oneOf:
            - $ref: "#/components/schemas/Observation_PlantTerrestial"
            - $ref: "#/components/schemas/Observation_PlantAquatic"
            - $ref: "#/components/schemas/Observation_AnimalTerrestrial"
            - $ref: "#/components/schemas/Observation_AnimalAquatic"
            

    Observation_PlantTerrestial:
      description: |
        Plant Observation Terrestrial
      type: object
      properties:
        species_density_code:
          type: string
          title: "Density"
        species_distribution_code:
          type: string
          title: "Distribution"
        soil_texture_code:
          type: string
          title: "Soil Texture"
        specific_use_code:
          type: string
          title: "Specific Use"
        slope_code:
          type: string
          title: "Slope"
        aspect_code:
          type: string
          title: "Aspect"
        proposed_action_code:
          type: string
          title: "Proposed Action"
        flowering:
          type: boolean
          title: "Flowering"
        plant_life_stage:
          type: string
          title: "Life Stage"
        plant_health:
          type: string
          title: "Health"
        plant_seed_stage:
          type: string
          title: "Seed Stage"
        sample_identifier:
          type: string
          title: "Sample ID"
        range_unit_number:
          type: string
          title: "Range Unit"
        legacy_site_ind:
          type: boolean
        early_detection_rapid_resp_ind:
          type: boolean
          title: "Early Detection"
        research_detection_ind:
          type: boolean
          title: "Research Detection"
        well_ind:
          type: boolean
          title: "Well"
        special_care_ind:
          type: boolean
          title: "Special Care"
        biological_ind:
          type: boolean
          title: "Biological"

    Observation_PlantAquatic:
      description:
        Plant Observation Terrestrial
      type: object
      properties:
        specific_use_code:
          type: string
          title: "Specific Use"
        proposed_action_code:
          type: string
          title: "Proposed Action"
        flowering:
          type: boolean
          title: "Flowering"
        plant_life_stage:
          type: string
          title: "Life Stage"
        plant_health:
          type: string
          title: "Health"
        plant_seed_stage:
          type: string
          title: "Seed Stage"
        sample_identifier:
          type: string
          title: "Sample ID"
        range_unit_number:
          type: string
          title: "Range Unit"
        legacy_site_ind:
          type: boolean
        early_detection_rapid_resp_ind:
          type: boolean
          title: "Early Detection"
        research_detection_ind:
          type: boolean
          title: "Research Detection"
        sample_taken:
          type: boolean
          title: "Sample Taken"
        sample_point_number:
          type: string
          title: "Sample Number"
        special_care_ind:
          type: boolean
          title: "Special Care"
        biological_ind:
          type: boolean
          title: "Biological"
        secchi_depth:
          type: number
          format: float
          title: "secchi depth"
        water_depth:
          type: number
          format: float
          title: "water depth"
        voucher_submitted_ind:
          type: boolean
          title: "Voucher submitted"
        voucher_submission_detail:
          type: string
          title: "Voucher submission details"
        

    Observation_AnimalTerrestrial:
      description: |
        Animal Observation Terrestrial.
      type: object
      properties:
        Number_of_Individuals_observed:
          type: number
          title: "Number of Individuals"
        Life_Stage:
          type: string
          title: "Life Stage"
        Behaviour:
          type: string
          title: "Behaviour"
  
        
    Observation_AnimalAquatic:
      description: |
        Animal Observation Aquatic.
      type: object
      properties:
        observation_details:
          type: string
          title: "Aquatic animal observations"


    Treatment:
      description: |
        Treament main object.
      type: object
      required:
        - treatment_method
        - treatment_date
        - treatment_time
      properties:
        treatment_method:
          type: string
          title: "Treatment method"
        treatment_date:
          type: string
          title: "Treatment date"
        treatment_time:
          type: string
          title: "Treatment time"
  
    Treatment_ChemicalPlant:
      description: |
        Chemical treament for plants - main object.
      type: object
      required:
        - primary_applicator_employee_code
        - secondary_applicator_employee_code
        - pesticide_employer_code
      properties:
        primary_applicator_employee_code:
          type: string
          title: "Primary Applicator employee code"
        secondary_applicator_employee_code:
          type: string
          title: "Secondary Applicator employee code"
        pesticide_employer_code:
          type: string
          title: "Pesticide employer code"
        project_management_plan_PMP:
          type: string
          title: "Projecty Management Plan"
        pesticide_use_permit_PUP:
          type: string
          title: "Pesticide use permit"
        chemical_treatment_method:
          type: string
          title: "Chemical treatment method"
        temperature:
          type: integer
          title: "Temperature"
        wind_speed:
          type: string
          title: "Wind"
        humidity:
          type: integer
          title: "Humidity"
        mix_delivery_rate:
          type: number
          format: float
          title: "Mix delivery rate"
        application_rate:
          type: number
          format: float
          title: "Application rate"
        area_treated:
          type: number
          format: float
          title: "Area treated"
        amount_of_herbicide_1:
          type: number
          format: float
          title: "Herbicide 1 amount"
        amount_of_herbicide_2:
          type: number
          format: float
          title: "Herbicide 2 amount"
        amount_of_herbicide_3:
          type: number
          format: float
          title: "Herbicide 3 amount"
        herbicide_1:
          type: string
          title: "Herbicide 1"
        herbicide_2:
          type: string
          title: "Herbicide 2"
        herbicide_3:
          type: string
          title: "Herbicide 3"

    Treatment_MechanicalPlant:
      description:
        Mechanical treament for plants - main object.
      type: object
      required:
        - mechanical_method
      properties:
        applicator1_first_name:
          type: string
          title: "Applicator 1 first name"
        applicator1_last_name:
          type: string
          title: "Applicator 1 last name"
        applicator2_first_name:
          type: string
          title: "Applicator 1 first name"
        applicator2_last_name:
          type: string
          title: "Applicator 1 last name"
        treatment_contractor:
          type: string
          title: "Treatment contractor"
        mechanical_method:
          type: string
          title: "Mechanical method"
        mechanical_disposal_method:
          type: string
          title: "Mechanical disposal method"
        mechanical_root_removal_code:
          type: string
          title: "Mechanical root removal code"
        mechanical_soil_disturbance_code:
          type: string
          title: "Mechanical soil disturbance code"
        signage_on_site:
          type: boolean
          title: "Signage on site"


  









    Media:
      description: |
        List of Media
      type: object
      properties:
        media_date:
          type: string
          title: "Date"
        description:
          type: string
          title: "Description"
        file_name: 
          type: 'string'
          title: 'File Name'
        encoded_file:
          type: 'string'
          format: 'base64'
          description: 'A Data URL base64 encoded image'
          example: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEBLAEsAAD/4REy...'
    
      
      
      
    
      
      

    

    

    
