from .observation_terrestrial import (
    EMPTY_TERRESTRIAL_OBSERVATION,
    MINIMAL_TERRESTRIAL_OBSERVATION,
    UPDATED_TERRESTRIAL_OBSERVATION,
)
from .observation_aquatic import (
    EMPTY_AQUATIC_OBSERVATION,
    MINIMAL_AQUATIC_OBSERVATION,
    UPDATED_AQUATIC_OBSERVATION,
)
from .chem_treatment_terrestrial import (
    EMPTY_CHEM_TREATMENT_TERRESTRIAL,
    MINIMAL_CHEM_TREATMENT_TERRESTRIAL,
    UPDATED_CHEM_TREATMENT_TERRESTRIAL,
)
from .chem_treatment_aquatic import (
    EMPTY_CHEM_TREATMENT_AQUATIC,
    MINIMAL_CHEM_TREATMENT_AQUATIC,
    UPDATED_CHEM_TREATMENT_AQUATIC,
)
from .mech_treatment_aquatic import (
    EMPTY_MECH_TREATMENT_AQUATIC,
    MINIMAL_MECH_TREATMENT_AQUATIC,
    UPDATED_MECH_TREATMENT_AQUATIC,
)
from .mech_treatment_terrestrial import (
    EMPTY_MECH_TREATMENT_TERRESTRIAL,
    MINIMAL_MECH_TREATMENT_TERRESTRIAL,
    UPDATED_MECH_TREATMENT_TERRESTRIAL,
)
from .biocontrol_release import (
    EMPTY_BIOCONTROL_RELEASE,
    MINIMAL_BIOCONTROL_RELEASE,
    UPDATED_BIOCONTROL_RELEASE,
)
from .biocontrol_collection import (
    EMPTY_BIOCONTROL_COLLECTION,
    MINIMAL_BIOCONTROL_COLLECTION,
    UPDATED_BIOCONTROL_COLLECTION,
)
from .biocontrol_dispersal_monitoring import (
    EMPTY_BIOCONTROL_DISPERSAL_MONITORING,
    MINIMAL_BIOCONTROL_DISPERSAL_MONITORING,
    UPDATED_BIOCONTROL_DISPERSAL_MONITORING,
)
from .biocontrol_release_monitoring import (
    EMPTY_BIOCONTROL_RELEASE_MONITORING,
    MINIMAL_BIOCONTROL_RELEASE_MONITORING,
    UPDATED_BIOCONTROL_RELEASE_MONITORING,
)
from .monitoring_chemical_treatment import (
    EMPTY_CHEM_TREATMENT_MONITORING,
    MINIMAL_CHEM_TREATMENT_MONITORING,
    UPDATED_CHEM_TREATMENT_MONITORING,
)
from .monitoring_mechanical_treatment import (
    EMPTY_MONITORING_MECH_TREATMENT,
    MINIMAL_MONITORING_MECH_TREATMENT,
    UPDATED_MONITORING_MECH_TREATMENT,
)
