from .observation_terrestrial import (
    MINIMAL_TERRESTRIAL_OBSERVATION,
    UPDATED_TERRESTRIAL_OBSERVATION,
)
from .observation_terrestrial import (
    MINIMAL_TERRESTRIAL_OBSERVATION,
    UPDATED_TERRESTRIAL_OBSERVATION,
)
from .chem_treatment_terrestrial import (
    MINIMAL_CHEM_TREATMENT_TERRESTRIAL,
    UPDATED_CHEM_TREATMENT_TERRESTRIAL,
)
from .chem_treatment_aquatic import (
    MINIMAL_CHEM_TREATMENT_AQUATIC,
    UPDATED_CHEM_TREATMENT_AQUATIC,
)
from .mech_treatment_aquatic import (
    MINIMAL_MECH_TREATMENT_AQUATIC,
    UPDATED_MECH_TREATMENT_AQUATIC,
)
from .mech_treatment_terrestrial import (
    MINIMAL_MECH_TREATMENT_TERRESTRIAL,
    UPDATED_MECH_TREATMENT_TERRESTRIAL,
)
from .biocontrol_release import MINIMAL_BIOCONTROL_RELEASE, UPDATED_BIOCONTROL_RELEASE
