EMPTY_BIOCONTROL_DISPERSAL_MONITORING = {
    "id": "f6784a14-27af-495f-a26d-7085e018d8c8",
    "short_id": "26PBDF6784A14",
    "employer": [],
    "subtype": "Biocontrol_Collection",
    "funding_agencies": [],
    "jurisdictions": [{"jurisdiction": "", "percent_covered": 0}],
    "projects": [],
    "location_description": "",
    "access_description": "",
    "form_status": "Draft",
    "date": "2026-06-25",
    "comment": "",
    "area_m": 0,
    "latitude": 0,
    "longitude": 0,
    "utm_zone": 0,
    "utm_easting": 0,
    "utm_northing": 0,
    "linked_activities": [],
    "participants": [{"name": ""}],
    "subtype_data": {
        "entries": [
            {
                "invasive_plant": "",
                "biological_agent": "",
                "collection_type": "",
                "collection_method": "",
                "start_time_collecting": "",
                "end_time_collecting": "",
                "comment": "",
                "actual_biological_agents": [{"quantity": 0, "stage": ""}],
                "estimated_biological_agents": [{"quantity": 0, "stage": ""}],
                "historical_iapp_site": None,
            }
        ],
        "target_plant_phenology": {
            "winter_dormant": 0,
            "seedlings": 0,
            "rosettes": 0,
            "bolts": 0,
            "flowering": 0,
            "seeds_forming": 0,
            "senescent": 0,
            "target_plant_heights": [{"height_cm": 0}],
        },
        "microsite_conditions": {"mesoslope_position": "", "site_surface_shape": ""},
        "weather_conditions": {
            "comments": "",
            "cloud_cover": "",
            "precipitation": "",
            "temperature": 0,
            "wind_direction": "",
            "wind_speed_kmh": 0,
        },
    },
    "type": "Biocontrol",
    "media": [],
    "created_by": "johnsmith@identifier",
}
EMPTY_BIOCONTROL_DISPERSAL_MONITORING = {
    "id": "1d72b730-b3dd-4614-9146-a49da0dad2b3",
    "short_id": "26PBD1D72B730",
    "employer": [],
    "subtype": "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial",
    "funding_agencies": [],
    "jurisdictions": [{"jurisdiction": "", "percent_covered": 0}],
    "projects": [],
    "location_description": "",
    "access_description": "",
    "form_status": "Draft",
    "date": "2026-06-25",
    "comment": "",
    "area_m": 0,
    "latitude": 0,
    "longitude": 0,
    "utm_zone": 0,
    "utm_easting": 0,
    "utm_northing": 0,
    "linked_activities": [],
    "participants": [{"name": ""}],
    "subtype_data": {
        "entries": [
            {
                "biocontrol_agent": "",
                "invasive_plant": "",
                "monitoring_type": "",
                "monitoring_method": "",
                "location_agent_found": [],
                "linear_segment": "",
                "sign_of_biocontrol_presence": [],
                "start_time": "",
                "stop_time": "",
                "suitable_for_collection": "",
                "actual_biological_agents": [
                    {
                        "quantity": 0,
                        "stage": "",
                        "plant_position": "",
                        "agent_location": "",
                    }
                ],
                "estimated_biological_agents": [
                    {
                        "quantity": 0,
                        "stage": "",
                        "plant_position": "",
                        "agent_location": "",
                    }
                ],
            }
        ],
        "target_plant_phenology": {
            "winter_dormant": 0,
            "seedlings": 0,
            "rosettes": 0,
            "bolts": 0,
            "flowering": 0,
            "seeds_forming": 0,
            "senescent": 0,
            "target_plant_heights": [{"height_cm": 0}],
        },
        "microsite_conditions": {"mesoslope_position": "", "site_surface_shape": ""},
        "weather_conditions": {
            "comments": "",
            "cloud_cover": "",
            "precipitation": "",
            "temperature": 0,
            "wind_direction": "",
            "wind_speed_kmh": 0,
        },
    },
    "type": "Monitoring",
    "media": [],
    "created_by": "johnsmith@identifier",
}

MINIMAL_BIOCONTROL_DISPERSAL_MONITORING = {
    "id": "f6784a14-27af-495f-a26d-7085e018d8c8",
    "short_id": "26PBDF6784A14",
    "employer": [{"employer": "MOTI"}],
    "subtype": "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial",
    "funding_agencies": [{"invasive_species_agency_code": "MOTI"}],
    "jurisdictions": [{"jurisdiction": "MOTI", "percent_covered": 100}],
    "projects": [{"description": "Description"}],
    "location_description": "Location Description",
    "access_description": "",
    "form_status": "Draft",
    "date": "2026-06-09",
    "comment": "",
    "area_m": 5,
    "latitude": 48.412053,
    "longitude": -123.36243,
    "utm_zone": 10,
    "utm_easting": 473180,
    "utm_northing": 5362163,
    "linked_activities": [],
    "participants": [{"name": "John Titor"}],
    "subtype_data": {
        "entries": [
            {
                "biocontrol_agent": "APHAITA",
                "biocontrol_present": False,
                "invasive_plant": "JK",
                "monitoring_type": "Timed",
                "monitoring_method": "Ex",
                "count_duration_minutes": 22,
                "location_agent_found": [],
                "linear_segment": "Yes",
                "sign_of_biocontrol_presence": [],
                "start_time": "2026-06-07T22:02",
                "stop_time": "2026-06-08T03:33",
                "suitable_for_collection": "",
                "actual_biological_agents": [],
                "estimated_biological_agents": [],
            }
        ],
        "microsite_conditions": {
            "mesoslope_position": "NA",
            "site_surface_shape": "NA",
        },
        "weather_conditions": {
            "comments": "",
            "cloud_cover": "2",
            "precipitation": "NA",
            "temperature": 0,
            "wind_direction": "N",
            "wind_speed_kmh": 22,
        },
    },
    "type": "Monitoring",
    "media": [],
    "created_by": "johnsmith@identifier",
    "shape": {
        "type": "Feature",
        "properties": {"error": "false"},
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [-123.36243032128927, 48.41206471411997],
                    [-123.36244305910944, 48.41206121195712],
                    [-123.3624483352843, 48.41205275698907],
                    [-123.3624430591052, 48.412044302022416],
                    [-123.36243032128927, 48.412040799860975],
                    [-123.36241758347336, 48.412044302022416],
                    [-123.36241230729426, 48.41205275698907],
                    [-123.36241758346911, 48.41206121195712],
                    [-123.36243032128927, 48.41206471411997],
                ]
            ],
        },
    },
}
UPDATED_BIOCONTROL_DISPERSAL_MONITORING = {
    "id": "f6784a14-27af-495f-a26d-7085e018d8c8",
    "short_id": "26PBDF6784A14",
    "employer": [{"employer": "MOTI"}],
    "subtype": "Monitoring_Biocontrol_Dispersal_Plant_Terrestrial",
    "funding_agencies": [{"invasive_species_agency_code": "MOTI"}],
    "jurisdictions": [{"jurisdiction": "MOTI", "percent_covered": 100}],
    "projects": [{"description": "Description"}],
    "location_description": "Location Description",
    "access_description": "Access Description",
    "form_status": "Submitted",
    "date": "2026-06-09",
    "comment": "General Comment",
    "area_m": 5,
    "latitude": 48.412053,
    "longitude": -123.36243,
    "utm_zone": 10,
    "utm_easting": 473180,
    "utm_northing": 5362163,
    "linked_activities": [],
    "participants": [{"name": "John Smith"}],
    "subtype_data": {
        "entries": [
            {
                "biocontrol_agent": "APHAITA",
                "biocontrol_present": True,
                "invasive_plant": "JK",
                "monitoring_type": "Timed",
                "monitoring_method": "Ex",
                "count_duration_minutes": 22,
                "location_agent_found": ["BS"],
                "linear_segment": "Yes",
                "sign_of_biocontrol_presence": ["CY"],
                "start_time": "2026-06-07T22:02",
                "stop_time": "2026-06-08T03:33",
                "suitable_for_collection": "Yes",
                "actual_biological_agents": [
                    {
                        "quantity": 444,
                        "stage": "AD",
                        "plant_position": "Bg",
                        "agent_location": "Ax",
                    }
                ],
                "estimated_biological_agents": [
                    {
                        "quantity": 222,
                        "stage": "LA",
                        "plant_position": "Is",
                        "agent_location": "Ax",
                    }
                ],
            }
        ],
        "target_plant_phenology": {
            "winter_dormant": 11,
            "seedlings": 12,
            "rosettes": 13,
            "bolts": 14,
            "flowering": 15,
            "seeds_forming": 16,
            "senescent": 19,
            "target_plant_heights": [
                {"height_cm": 3},
                {"height_cm": 6},
                {"height_cm": 9},
            ],
        },
        "microsite_conditions": {
            "mesoslope_position": "NA",
            "site_surface_shape": "NA",
        },
        "weather_conditions": {
            "comments": "Weather Comments",
            "cloud_cover": "2",
            "precipitation": "NA",
            "temperature": 0,
            "wind_direction": "N",
            "wind_speed_kmh": 22,
        },
    },
    "type": "Biocontrol",
    "media": [],
    "created_by": "johnsmith@identifier",
    "shape": {
        "type": "Feature",
        "properties": {"error": "false"},
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [-123.36243032128927, 48.41206471411997],
                    [-123.36244305910944, 48.41206121195712],
                    [-123.3624483352843, 48.41205275698907],
                    [-123.3624430591052, 48.412044302022416],
                    [-123.36243032128927, 48.412040799860975],
                    [-123.36241758347336, 48.412044302022416],
                    [-123.36241230729426, 48.41205275698907],
                    [-123.36241758346911, 48.41206121195712],
                    [-123.36243032128927, 48.41206471411997],
                ]
            ],
        },
    },
}
