name: State tests for web app
on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install sharedAPI
        run: |
          cd sharedAPI
          npm install --legacy-peer-deps
          cd ../app
          npm install

      - name: Test
        env:
          MOBILE: false
          JEEPSQLITE: 'FALSE'
          REDIRECT_URI: ''
          IAPP_GEOJSON_URL: 'banana'
          REACT_APP_API_HOST: 'http://localhost:3002'
          SSO_CLIENT_ID: ''
          SSO_REALM: ''
          PUBLIC_MAP_URL: ''
          CONFIGURATION_SOURCE: 'Provided'
          OPENSHIFT_BUILD_COMMIT: ''
          SOURCE_GIT_COMMIT: $GITHUB_SHA
        run: |
          cd app
          npm run test

