name: "Web app state test coverage"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - ${{ github.head_ref }}
          - "dev"

    permissions:
      # Required to checkout the code
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install 
        run: |
          cd sharedAPI
          npm install --legacy-peer-deps
          cd ../app
          npm install
      - name: "Test"
        env:
          MOBILE: false
          JEEPSQLITE: 'FALSE'
          REDIRECT_URI: ''
          IAPP_GEOJSON_URL: 'banana'
          REACT_APP_API_HOST: 'http://localhost:3002'
          SSO_CLIENT_ID: ''
          SSO_REALM: ''
          PUBLIC_MAP_URL: ''
          CONFIGURATION_SOURCE: 'Provided'
          OPENSHIFT_BUILD_COMMIT: ''
          SOURCE_GIT_COMMIT: $GITHUB_SHA
        run: cd app && npm run state_test_coverage_gh
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.branch }}
          path: app/src/coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: "Download Coverage Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ github.head_ref }}
          path: coverage
      - uses: actions/download-artifact@v4
        with:
          name: coverage-dev
          path: coverage-dev
      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-dev/coverage-summary.json
