# Clean out the deployment artifacts when a PR is closed.
# This deletes the PR artifacts created by the deploy-pr workflow.

# This workflow only runs if the PR has either the 'PR-DEPLOY' label and/or 'PR-DEPLOY' in the title when it is first created.
# If the label or title are updated after the PR has been opened, you will need to push a change to the PR to re-trigger the workflow.
# Manually re-running the workflow (via the 're-run jobs' button) won't work, as the git context won't have updated and the new label and/or title won't be present.
name: Clean PR Deploy Artifacts

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - test
      - prod

jobs:
  # Print variables for logging and debugging purposes
  checkEnv:
    name: Check Env variables
    runs-on: ubuntu-16.04
    if: ${{ contains(github.event.pull_request.labels.*.name, 'PR-DEPLOY') || contains(github.event.pull_request.title, 'PR-DEPLOY') }}
    env:
      LABELS: ${{ toJson(github.event.pull_request.labels) }}
    steps:
      - name: Print Env Vars
        run: |
          echo OC CLI Version: $(oc version)
          echo Git Base Ref: ${{ github.base_ref }}
          echo Git Change ID: ${{ github.event.number }}
          echo Git Pull Request Ref: ${{ github.event.pull_request.head.sha }}
          echo GIt Event Name: ${{ github.event_name }}
          echo GIt Event Action: ${{ github.event.action }}
          echo Git Title: ${{ github.event.pull_request.title }}
          echo Git Labels: "$LABELS"

  clean:
    name: Clean Build and Deployment Artifacts in the Dev and Tools OpenShift environments
    runs-on: ubuntu-16.04
    # Only clean if the PR that closed was marked as a PR-DEPLOY
    if: ${{ contains(github.event.pull_request.labels.*.name, 'PR-DEPLOY') || contains(github.event.pull_request.title, 'PR-DEPLOY') }}
    env:
      BUILD_ID: ${{ github.event.number }}
    steps:
      # Checkout the PR branch
      - name: Checkout Dev Branch - Contains the Pipeline Code
        uses: actions/checkout@v2

      # Install Node - for `node` and `npm` commands
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.16

      # Log in to OpenShift.
      # Note: The secrets needed to log in are NOT available if the PR comes from a FORK.
      # PR's must originate from a branch off the original repo or else all openshift `oc` commands will fail.
      - name: Log in to OpenShift
        run: oc login --token=${{ secrets.TOOLS_SA_TOKEN }} --server=https://api.silver.devops.gov.bc.ca:6443

      # Clean the database build/deployment artifacts
      - name: Clean Database Artifacts
        working-directory: './database/.pipeline/'
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev

      # Clean the api build/deployment artifacts
      - name: Clean API Artifacts
        working-directory: './api/.pipeline/'
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev

      # Clean the app build/deployment artifacts
      - name: Clean APP Artifacts
        working-directory: './app/.pipeline/'
        run: |
          npm ci
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=build
          DEBUG=* npm run clean -- --pr=$BUILD_ID --env=dev
